# Development Configuration
dynaconf_merge: true
development:
  env: development

  debug: true

  api:
    reload: true

  # Sandbox Configuration for Development
  sandbox:
    enabled: true
    domain: "localhost:8090"
    image: "hub.sensedeal.vip/library/cubebox-sandbox:24.04-20260311"

  mcp:
    enabled: true
    servers:
      webtools:
        url: "http://localhost:8020/api/webtools"
        transport: streamable_http
        key: "Pu9bKu1h9yGd9slVf9c9ugxCYd7f3f0V=="
        tools:
          - name: web_search
            content_type: json
          - name: web_fetch
            content_type: text
        enabled: true
