"""Builtin tools ported to cubepi (M2.1) — unit tests."""

from __future__ import annotations

import re

import pytest

from cubeplex.tools.builtin.calculator import calculator_tool
from cubeplex.tools.builtin.datetime_tool import datetime_tool
from cubeplex.tools.builtin.view_images import ViewImagesInput, make_view_images_tool

# The two pure-function builtins use @cubepi.tool; their input schemas are
# auto-generated by the decorator, so construct args via ``tool.parameters(...)``.
CalculatorInput = calculator_tool.parameters
DateTimeInput = datetime_tool.parameters

# ---------------------------------------------------------------------------
# Calculator
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_calculator_tool_basic_arithmetic() -> None:
    args = CalculatorInput(expression="2 + 3 * 4")
    result = await calculator_tool.execute("tc-1", args, signal=None, on_update=None)
    assert len(result.content) == 1
    assert "14" in result.content[0].text


@pytest.mark.asyncio
async def test_calculator_tool_division() -> None:
    args = CalculatorInput(expression="10 / 4")
    result = await calculator_tool.execute("tc-div", args, signal=None, on_update=None)
    assert "2.5" in result.content[0].text


@pytest.mark.asyncio
async def test_calculator_tool_zero_division_returns_error_text() -> None:
    args = CalculatorInput(expression="1 / 0")
    result = await calculator_tool.execute("tc-zdiv", args, signal=None, on_update=None)
    assert isinstance(result.content[0].text, str)
    assert "error" in result.content[0].text.lower()


@pytest.mark.asyncio
async def test_calculator_tool_invalid_expression_returns_error_text() -> None:
    """Calculator should not raise; it returns an error message in content."""
    args = CalculatorInput(expression="import os")
    result = await calculator_tool.execute("tc-2", args, signal=None, on_update=None)
    assert isinstance(result.content[0].text, str)
    # Must not propagate as an exception — just a text error.


def test_calculator_tool_metadata() -> None:
    assert calculator_tool.name == "calculator"
    desc_lower = calculator_tool.description.lower()
    assert "math" in desc_lower or "calc" in desc_lower


def test_calculator_tool_parameters_is_pydantic_model() -> None:
    from pydantic import BaseModel

    assert issubclass(calculator_tool.parameters, BaseModel)


# ---------------------------------------------------------------------------
# DateTime
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_datetime_tool_returns_date_string() -> None:
    args = DateTimeInput()
    result = await datetime_tool.execute("tc-3", args, signal=None, on_update=None)
    assert len(result.content) >= 1
    text = result.content[0].text
    assert re.search(r"\d{4}", text), f"no year in: {text!r}"


@pytest.mark.asyncio
async def test_datetime_tool_with_time_includes_colon() -> None:
    args = DateTimeInput(include_time=True)
    result = await datetime_tool.execute("tc-4", args, signal=None, on_update=None)
    text = result.content[0].text
    # HH:MM:SS format must be present
    assert re.search(r"\d{2}:\d{2}:\d{2}", text), f"no time in: {text!r}"


@pytest.mark.asyncio
async def test_datetime_tool_default_omits_time() -> None:
    args = DateTimeInput(include_time=False)
    result = await datetime_tool.execute("tc-5", args, signal=None, on_update=None)
    text = result.content[0].text
    # Without include_time the strftime has no colons
    assert ":" not in text, f"unexpected time in: {text!r}"


def test_datetime_tool_metadata() -> None:
    assert datetime_tool.name in ("datetime", "current_datetime", "get_datetime")


def test_datetime_tool_parameters_is_pydantic_model() -> None:
    from pydantic import BaseModel

    assert issubclass(datetime_tool.parameters, BaseModel)


# ---------------------------------------------------------------------------
# view_images — factory shape only (no sandbox needed for shape tests)
# ---------------------------------------------------------------------------


def test_view_images_factory_returns_agent_tool() -> None:
    """make_view_images_tool returns a properly shaped AgentTool."""
    from unittest.mock import MagicMock

    from cubepi.agent.types import AgentTool

    mock_objectstore = MagicMock()
    mock_capabilities = MagicMock()
    mock_capabilities.supports_image.return_value = True

    tool = make_view_images_tool(
        org_id="org-1",
        workspace_id="ws-1",
        objectstore=mock_objectstore,
        capabilities=mock_capabilities,
    )

    assert isinstance(tool, AgentTool)
    assert tool.name == "view_images"
    assert "image" in tool.description.lower()


def test_view_images_parameters_schema() -> None:
    from unittest.mock import MagicMock

    from pydantic import BaseModel

    mock_objectstore = MagicMock()
    mock_capabilities = MagicMock()
    mock_capabilities.supports_image.return_value = True

    tool = make_view_images_tool(
        org_id="org-1",
        workspace_id="ws-1",
        objectstore=mock_objectstore,
        capabilities=mock_capabilities,
    )
    assert issubclass(tool.parameters, BaseModel)
    assert tool.parameters is ViewImagesInput


@pytest.mark.asyncio
async def test_view_images_returns_error_when_model_has_no_image_support() -> None:
    from unittest.mock import MagicMock

    mock_objectstore = MagicMock()
    mock_capabilities = MagicMock()
    mock_capabilities.supports_image.return_value = False

    tool = make_view_images_tool(
        org_id="org-1",
        workspace_id="ws-1",
        objectstore=mock_objectstore,
        capabilities=mock_capabilities,
    )
    args = ViewImagesInput(paths=["/sandbox/img.jpg"])
    result = await tool.execute("tc-vi-1", args, signal=None, on_update=None)
    assert result.is_error is True
    assert "not support" in result.content[0].text.lower()


@pytest.mark.asyncio
async def test_view_images_does_not_cold_start_lazy_sandbox() -> None:
    """User-uploaded images live in ObjectStore. Hitting sandbox.download on
    an unused LazySandbox would provision a container before the fallback."""
    from collections.abc import AsyncGenerator
    from contextlib import asynccontextmanager
    from unittest.mock import AsyncMock, MagicMock, patch

    sandbox = MagicMock()
    sandbox.initialized = False
    sandbox.download = AsyncMock(side_effect=AssertionError("must not cold-start"))

    mock_objectstore = MagicMock()
    mock_capabilities = MagicMock()
    mock_capabilities.supports_image.return_value = True

    repo = MagicMock()
    repo.find_by_sandbox_path = AsyncMock(return_value=None)

    @asynccontextmanager
    async def _ses() -> AsyncGenerator[MagicMock, None]:
        yield MagicMock()

    tool = make_view_images_tool(
        org_id="org-1",
        workspace_id="ws-1",
        objectstore=mock_objectstore,
        capabilities=mock_capabilities,
        sandbox=sandbox,
    )
    args = ViewImagesInput(paths=["/workspace/uploads/c1/a.png"])
    with (
        patch("cubeplex.db.engine.async_session_maker", _ses),
        patch("cubeplex.repositories.AttachmentRepository", MagicMock(return_value=repo)),
    ):
        result = await tool.execute("tc-vi-2", args, signal=None, on_update=None)

    sandbox.download.assert_not_called()
    assert not result.is_error
    assert "image not found" in result.content[-1].text


@pytest.mark.asyncio
async def test_view_images_reads_initialized_sandbox_first() -> None:
    from collections.abc import AsyncGenerator
    from contextlib import asynccontextmanager
    from unittest.mock import AsyncMock, MagicMock, patch

    sandbox = MagicMock()
    sandbox.initialized = True
    sandbox.download = AsyncMock(return_value=[("/workspace/shot.png", b"not-an-image")])

    mock_objectstore = MagicMock()
    mock_objectstore.download_file = AsyncMock()
    mock_capabilities = MagicMock()
    mock_capabilities.supports_image.return_value = True

    @asynccontextmanager
    async def _ses() -> AsyncGenerator[MagicMock, None]:
        yield MagicMock()

    tool = make_view_images_tool(
        org_id="org-1",
        workspace_id="ws-1",
        objectstore=mock_objectstore,
        capabilities=mock_capabilities,
        sandbox=sandbox,
    )
    args = ViewImagesInput(paths=["/workspace/shot.png"])
    with (
        patch("cubeplex.db.engine.async_session_maker", _ses),
        patch("cubeplex.repositories.AttachmentRepository", MagicMock()),
    ):
        result = await tool.execute("tc-vi-3", args, signal=None, on_update=None)

    sandbox.download.assert_awaited_once_with(["/workspace/shot.png"])
    mock_objectstore.download_file.assert_not_called()
    # Bytes are not a real image, so resize fails and we report the error.
    assert "error" in result.content[-1].text.lower()
