{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cubebox.fullname" . }}
  labels:
    {{- include "cubebox.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ printf "%s-tls" (include "cubebox.fullname" .) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cubebox.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "cubebox.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cubebox.frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
