"""add im_channel_bindings table

Revision ID: 00fe892184fa
Revises: 59fd2d03ce79
Create Date: 2026-06-19 00:02:22.225347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '00fe892184fa'
down_revision: Union[str, Sequence[str], None] = '59fd2d03ce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('im_channel_bindings',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('sandbox_mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_im_channel_binding_account', 'im_channel_bindings', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_channel_bindings_org_id'), 'im_channel_bindings', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_channel_bindings_workspace_id'), 'im_channel_bindings', ['workspace_id'], unique=False)
    op.create_index('uq_im_channel_binding', 'im_channel_bindings', ['account_id', 'channel_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_im_channel_binding', table_name='im_channel_bindings')
    op.drop_index(op.f('ix_im_channel_bindings_workspace_id'), table_name='im_channel_bindings')
    op.drop_index(op.f('ix_im_channel_bindings_org_id'), table_name='im_channel_bindings')
    op.drop_index('ix_im_channel_binding_account', table_name='im_channel_bindings')
    op.drop_table('im_channel_bindings')
