"""add sandbox_commands

Revision ID: 017a7aad922f
Revises: a20bbb53ccff
Create Date: 2026-09-18 06:13:07.749257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '017a7aad922f'
down_revision: Union[str, Sequence[str], None] = 'a20bbb53ccff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_commands',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_sandbox_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('started_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('provider_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notify_on_complete', sa.Boolean(), nullable=False),
    sa.Column('notice_state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('log_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('log_cursor', sa.String(length=64), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('owner_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_sandbox_id'], ['user_sandboxes.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_commands_conversation_id'), 'sandbox_commands', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sandbox_commands_org_id'), 'sandbox_commands', ['org_id'], unique=False)
    op.create_index('ix_sandbox_commands_org_ws', 'sandbox_commands', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_sandbox_commands_run_id'), 'sandbox_commands', ['run_id'], unique=False)
    op.create_index('ix_sandbox_commands_run_status', 'sandbox_commands', ['run_id', 'status'], unique=False)
    op.create_index('ix_sandbox_commands_sandbox_status', 'sandbox_commands', ['user_sandbox_id', 'status'], unique=False)
    op.create_index(op.f('ix_sandbox_commands_user_sandbox_id'), 'sandbox_commands', ['user_sandbox_id'], unique=False)
    op.create_index(op.f('ix_sandbox_commands_workspace_id'), 'sandbox_commands', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_commands_workspace_id'), table_name='sandbox_commands')
    op.drop_index(op.f('ix_sandbox_commands_user_sandbox_id'), table_name='sandbox_commands')
    op.drop_index('ix_sandbox_commands_sandbox_status', table_name='sandbox_commands')
    op.drop_index('ix_sandbox_commands_run_status', table_name='sandbox_commands')
    op.drop_index(op.f('ix_sandbox_commands_run_id'), table_name='sandbox_commands')
    op.drop_index('ix_sandbox_commands_org_ws', table_name='sandbox_commands')
    op.drop_index(op.f('ix_sandbox_commands_org_id'), table_name='sandbox_commands')
    op.drop_index(op.f('ix_sandbox_commands_conversation_id'), table_name='sandbox_commands')
    op.drop_table('sandbox_commands')
    # ### end Alembic commands ###
