"""require background task command binding

Revision ID: 034d0feb3d1e
Revises: 76a2d219d682
Create Date: 2026-09-23 05:29:18.902866

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "034d0feb3d1e"
down_revision: str | Sequence[str] | None = "76a2d219d682"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandbox_commands", "task_id", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sandbox_commands", "task_id", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###
