"""merge sandbox-env/egress heads with main

Revision ID: 03cadabcebbc
Revises: 6c69cc288404, 1890ff8246f4
Create Date: 2026-05-26 09:46:42.683093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '03cadabcebbc'
down_revision: Union[str, Sequence[str], None] = ('6c69cc288404', '1890ff8246f4')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
