"""expand background task lifecycle storage

Revision ID: 0430ad3006d8
Revises: b2141c3f7682
Create Date: 2026-09-21 03:31:42.479974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '0430ad3006d8'
down_revision: Union[str, Sequence[str], None] = 'b2141c3f7682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_execution_admissions',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('execution_generation', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.CheckConstraint('execution_generation >= 0', name='ck_execution_admission_generation'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'workspace_id', 'source_kind', 'source_id', name='uq_execution_source')
    )
    op.create_index(op.f('ix_conversation_execution_admissions_org_id'), 'conversation_execution_admissions', ['org_id'], unique=False)
    op.create_index('ix_conversation_execution_admissions_org_ws', 'conversation_execution_admissions', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_conversation_execution_admissions_workspace_id'), 'conversation_execution_admissions', ['workspace_id'], unique=False)
    op.create_index('ix_execution_admissions_conv_gen', 'conversation_execution_admissions', ['conversation_id', 'execution_generation'], unique=False)
    op.create_table('background_tasks',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('admission_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parent_task_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('originating_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('started_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('execution_generation', sa.BigInteger(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notify_on_complete', sa.Boolean(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('notifications_cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('owner_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backgrounded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_ref', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('execution_generation >= 0', name='ck_background_task_generation'),
    sa.CheckConstraint('parent_task_id IS NULL OR parent_task_id <> id', name='ck_task_parent'),
    sa.CheckConstraint('revision >= 0', name='ck_background_task_revision'),
    sa.ForeignKeyConstraint(['admission_id'], ['conversation_execution_admissions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['background_tasks.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_id', 'originating_run_id', 'tool_call_id', 'agent_id', name='uq_background_task_tool_call', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_background_tasks_claim', 'background_tasks', ['state', 'owner_until', 'id'], unique=False)
    op.create_index('ix_background_tasks_conv_state', 'background_tasks', ['conversation_id', 'state'], unique=False)
    op.create_index(op.f('ix_background_tasks_org_id'), 'background_tasks', ['org_id'], unique=False)
    op.create_index('ix_background_tasks_org_ws', 'background_tasks', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_background_tasks_parent_task_id'), 'background_tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_background_tasks_workspace_id'), 'background_tasks', ['workspace_id'], unique=False)
    op.create_table('background_task_events',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('execution_generation', sa.BigInteger(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('result_ref', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('discard_reason', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('owner_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('owner_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('delivery_attempt_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('delivery_input_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('checkpoint_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('checkpoint_input_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['background_tasks.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'dedupe_key', name='uq_background_task_event_dedupe')
    )
    op.create_index('ix_background_task_events_claim', 'background_task_events', ['state', 'owner_until', 'id'], unique=False)
    op.create_index(op.f('ix_background_task_events_org_id'), 'background_task_events', ['org_id'], unique=False)
    op.create_index('ix_background_task_events_org_ws', 'background_task_events', ['org_id', 'workspace_id'], unique=False)
    op.create_index('ix_background_task_events_pending', 'background_task_events', ['conversation_id', 'state', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_background_task_events_task_id'), 'background_task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_background_task_events_workspace_id'), 'background_task_events', ['workspace_id'], unique=False)
    op.add_column('conversations', sa.Column('execution_generation', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('execution_closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sandbox_commands', sa.Column('task_id', sa.String(length=20), nullable=True))
    op.add_column('sandbox_commands', sa.Column('sandbox_instance_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sandbox_commands', sa.Column('log_state', sqlmodel.sql.sqltypes.AutoString(length=20), server_default='pending', nullable=False))
    op.create_unique_constraint('uq_sandbox_commands_task_id', 'sandbox_commands', ['task_id'])
    op.create_foreign_key('fk_sandbox_commands_task_id', 'sandbox_commands', 'background_tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sandbox_commands_task_id', 'sandbox_commands', type_='foreignkey')
    op.drop_constraint('uq_sandbox_commands_task_id', 'sandbox_commands', type_='unique')
    op.drop_column('sandbox_commands', 'log_state')
    op.drop_column('sandbox_commands', 'sandbox_instance_id')
    op.drop_column('sandbox_commands', 'task_id')
    op.drop_column('conversations', 'execution_closed_at')
    op.drop_column('conversations', 'execution_generation')
    op.drop_index(op.f('ix_background_task_events_workspace_id'), table_name='background_task_events')
    op.drop_index(op.f('ix_background_task_events_task_id'), table_name='background_task_events')
    op.drop_index('ix_background_task_events_pending', table_name='background_task_events')
    op.drop_index('ix_background_task_events_org_ws', table_name='background_task_events')
    op.drop_index(op.f('ix_background_task_events_org_id'), table_name='background_task_events')
    op.drop_index('ix_background_task_events_claim', table_name='background_task_events')
    op.drop_table('background_task_events')
    op.drop_index(op.f('ix_background_tasks_workspace_id'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_parent_task_id'), table_name='background_tasks')
    op.drop_index('ix_background_tasks_org_ws', table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_org_id'), table_name='background_tasks')
    op.drop_index('ix_background_tasks_conv_state', table_name='background_tasks')
    op.drop_index('ix_background_tasks_claim', table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index('ix_execution_admissions_conv_gen', table_name='conversation_execution_admissions')
    op.drop_index(op.f('ix_conversation_execution_admissions_workspace_id'), table_name='conversation_execution_admissions')
    op.drop_index('ix_conversation_execution_admissions_org_ws', table_name='conversation_execution_admissions')
    op.drop_index(op.f('ix_conversation_execution_admissions_org_id'), table_name='conversation_execution_admissions')
    op.drop_table('conversation_execution_admissions')
    # ### end Alembic commands ###
