"""persist immutable conversation execution admissions

Revision ID: 06bb443b55ea
Revises: 17410d02fbaf
Create Date: 2026-09-21 06:25:18.559358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '06bb443b55ea'
down_revision: Union[str, Sequence[str], None] = '17410d02fbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_execution_admissions', sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('conversation_execution_admissions', sa.Column('resolved_execution', sa.JSON(), nullable=True))
    op.add_column('conversation_execution_admissions', sa.Column('run_start_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('conversation_execution_admissions', sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversation_execution_admissions', sa.Column('run_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversation_execution_admissions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_execution_admissions', 'revoked_at')
    op.drop_column('conversation_execution_admissions', 'run_finished_at')
    op.drop_column('conversation_execution_admissions', 'run_started_at')
    op.drop_column('conversation_execution_admissions', 'run_start_token')
    op.drop_column('conversation_execution_admissions', 'resolved_execution')
    op.drop_column('conversation_execution_admissions', 'request_fingerprint')
    # ### end Alembic commands ###
