"""mcp template centric semantics

Revision ID: 076f490b6099
Revises: a687284a937b
Create Date: 2026-07-09 23:37:28.770167

Downgrade is data-lossy in two ways:

1. mcp_credential_grants.auth_method is dropped and cannot be recovered on
   re-upgrade (connectors.auth_method was already removed, so the backfill
   would default everything to 'static', corrupting OAuth grants).

2. mcp_connector_templates rows with scope != 'global' (org- or
   workspace-scoped custom templates) are permanently deleted.  Re-upgrade
   synthesises replacements with supported_auth_methods=['none'], silently
   corrupting any connectors that used OAuth or static auth.

The downgrade() function refuses to proceed when either of these data shapes
is present.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

# revision identifiers, used by Alembic.
revision: str = '076f490b6099'
down_revision: Union[str, Sequence[str], None] = 'a687284a937b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Op ordering rationale:
    1. templates: add new scope/owner columns (server_default keeps existing rows
       as scope='global').  Add scope-shape check constraint.
    2. grants.auth_method: 3-step add-nullable → backfill from connector →
       tighten NOT NULL.  Add auth_method check constraint.
    3. Synthesize org-scope templates for custom connectors (template_id IS NULL),
       then link connectors to them.  Runs before auth cols are dropped because
       the INSERT reads c.auth_method and c.org_id.  Runs before template_id NOT
       NULL is enforced.
    4. Tighten connectors.template_id to NOT NULL.  Drop connectors.auth_method
       and connectors.auth_status.  Drop old auth check constraint.  Recreate
       the partial index without the "template_id IS NOT NULL" clause.
    5. Create mcp_connector_templates_settings table.
    """
    # ------------------------------------------------------------------
    # 1) templates: add scope + owner columns; add scope-shape constraint
    # ------------------------------------------------------------------
    op.add_column('mcp_connector_templates', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=16), server_default=sa.text("'global'"), nullable=False))
    op.add_column('mcp_connector_templates', sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('mcp_connector_templates', sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('mcp_connector_templates', sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_index(op.f('ix_mcp_connector_templates_org_id'), 'mcp_connector_templates', ['org_id'], unique=False)
    op.create_index(op.f('ix_mcp_connector_templates_workspace_id'), 'mcp_connector_templates', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'mcp_connector_templates', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'mcp_connector_templates', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'mcp_connector_templates', 'users', ['created_by_user_id'], ['id'])
    op.create_check_constraint(
        'ck_mcp_connector_templates_scope_shape',
        'mcp_connector_templates',
        "(scope='global' AND org_id IS NULL AND workspace_id IS NULL)"
        " OR (scope='org' AND org_id IS NOT NULL AND workspace_id IS NULL)"
        " OR (scope='workspace' AND org_id IS NOT NULL AND workspace_id IS NOT NULL)",
    )

    # ------------------------------------------------------------------
    # 2) grants.auth_method: add nullable → backfill → tighten; add check
    # ------------------------------------------------------------------
    op.add_column('mcp_credential_grants', sa.Column('auth_method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.execute(
        """
        UPDATE mcp_credential_grants g
        SET auth_method = COALESCE(NULLIF(c.auth_method, 'none'), 'static')
        FROM mcp_connectors c
        WHERE g.connector_id = c.id
        """
    )
    op.alter_column('mcp_credential_grants', 'auth_method', nullable=False)
    op.create_check_constraint(
        'ck_mcp_credential_grants_auth_method',
        'mcp_credential_grants',
        "auth_method IN ('oauth','static')",
    )

    # ------------------------------------------------------------------
    # 3) synthesize org-scope templates for custom connectors, then link.
    #    Runs BEFORE auth cols are dropped (reads c.auth_method) and BEFORE
    #    template_id goes NOT NULL.
    #    id = 'mctpl-' (6 chars) + substr(md5, 1, 14) = 20 chars (matches
    #    the varchar(20) id column).  supported_auth_methods is json type.
    # ------------------------------------------------------------------
    op.execute(
        """
        INSERT INTO mcp_connector_templates
            (id, slug, name, description, provider, server_url, transport,
             supported_auth_methods, default_credential_policy,
             static_auth_style, static_auth_header_name, static_auth_query_param,
             template_metadata, tool_citation_defaults, status,
             scope, org_id, workspace_id, created_by_user_id,
             created_at, updated_at)
        SELECT
            'mctpl-' || substr(md5(c.id), 1, 14),
            'custom-' || c.slug_name || '-' || lower(substr(c.org_id, length(c.org_id) - 5)),
            c.name, '', 'custom', c.server_url, c.transport,
            array_to_json(ARRAY[c.auth_method]),
            c.default_credential_policy,
            c.static_auth_style, c.static_auth_header_name, c.static_auth_query_param,
            '{}'::json, '{}'::json, 'active',
            'org', c.org_id, NULL, c.created_by_user_id,
            now(), now()
        FROM mcp_connectors c
        WHERE c.template_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE mcp_connectors c
        SET template_id = 'mctpl-' || substr(md5(c.id), 1, 14)
        WHERE c.template_id IS NULL
        """
    )

    # ------------------------------------------------------------------
    # 4) tighten template_id NOT NULL; drop auth cols + old check;
    #    recreate partial index without "template_id IS NOT NULL" clause
    # ------------------------------------------------------------------
    op.alter_column('mcp_connectors', 'template_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # Drop the old auth check constraint before dropping the column it covers
    op.drop_constraint('ck_mcp_connectors_auth_method', 'mcp_connectors', type_='check')
    op.drop_column('mcp_connectors', 'auth_method')
    op.drop_column('mcp_connectors', 'auth_status')
    # Recreate partial index without the "AND template_id IS NOT NULL" clause
    op.drop_index('uq_mcp_connector_template_per_org', table_name='mcp_connectors')
    op.create_index(
        'uq_mcp_connector_template_per_org',
        'mcp_connectors',
        ['org_id', 'template_id'],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )

    # ------------------------------------------------------------------
    # 5) create mcp_connector_templates_settings table
    # ------------------------------------------------------------------
    op.create_table('mcp_connector_templates_settings',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['mcp_connector_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'template_id', name='uq_mcp_connector_templates_settings')
    )
    op.create_index(op.f('ix_mcp_connector_templates_settings_org_id'), 'mcp_connector_templates_settings', ['org_id'], unique=False)
    op.create_index(op.f('ix_mcp_connector_templates_settings_template_id'), 'mcp_connector_templates_settings', ['template_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    Refuses to run when mcp_credential_grants rows exist: downgrading drops
    auth_method from grants, and re-upgrading cannot recover the original values
    (connectors.auth_method is already gone, so the backfill would default to
    'static', silently corrupting OAuth grants).  Delete all grants first, or
    restore from a pre-migration backup.
    """
    bind = op.get_bind()
    grant_count = bind.execute(sa.text("SELECT COUNT(*) FROM mcp_credential_grants")).scalar() or 0
    if grant_count:
        raise RuntimeError(
            "cannot downgrade template-centric migration: "
            f"{grant_count} mcp_credential_grants rows present would lose auth_method info. "
            "Delete grants before downgrading, or restore from a pre-migration backup."
        )

    scoped_template_count = (
        bind.execute(
            sa.text("SELECT COUNT(*) FROM mcp_connector_templates WHERE scope <> 'global'")
        ).scalar()
        or 0
    )
    if scoped_template_count:
        raise RuntimeError(
            "cannot downgrade template-centric migration: "
            f"{scoped_template_count} mcp_connector_templates rows with scope != 'global' present "
            "would be permanently deleted. Reduce to global-scope-only templates before "
            "downgrading, or restore from a pre-migration backup."
        )

    # Reverse step 5: drop settings table
    op.drop_index(op.f('ix_mcp_connector_templates_settings_template_id'), table_name='mcp_connector_templates_settings')
    op.drop_index(op.f('ix_mcp_connector_templates_settings_org_id'), table_name='mcp_connector_templates_settings')
    op.drop_table('mcp_connector_templates_settings')

    # Reverse step 4: restore partial index with IS NOT NULL clause, restore auth cols
    op.drop_index('uq_mcp_connector_template_per_org', table_name='mcp_connectors')
    op.create_index(
        'uq_mcp_connector_template_per_org',
        'mcp_connectors',
        ['org_id', 'template_id'],
        unique=True,
        postgresql_where=sa.text("status = 'active' AND template_id IS NOT NULL"),
    )
    op.add_column('mcp_connectors', sa.Column('auth_status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('mcp_connectors', sa.Column('auth_method', sa.VARCHAR(length=16), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False))
    op.create_check_constraint(
        'ck_mcp_connectors_auth_method',
        'mcp_connectors',
        "auth_method IN ('oauth','static','none')",
    )
    op.alter_column('mcp_connectors', 'template_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # Reverse step 3: remove synthesized templates (delete custom ones) and
    # unlink connectors. In downgrade we can only null out synthesized links
    # since the original template_id=NULL state is the pre-migration state.
    op.execute(
        """
        UPDATE mcp_connectors SET template_id = NULL
        WHERE template_id IN (
            SELECT id FROM mcp_connector_templates WHERE scope = 'org'
        )
        """
    )
    op.execute(
        "DELETE FROM mcp_connector_templates WHERE scope = 'org'"
    )

    # Reverse step 2: drop auth_method check and column from grants
    op.drop_constraint('ck_mcp_credential_grants_auth_method', 'mcp_credential_grants', type_='check')
    op.drop_column('mcp_credential_grants', 'auth_method')

    # Reverse step 1: drop scope/owner cols and indexes from templates
    op.drop_constraint('ck_mcp_connector_templates_scope_shape', 'mcp_connector_templates', type_='check')
    op.drop_constraint(None, 'mcp_connector_templates', type_='foreignkey')
    op.drop_constraint(None, 'mcp_connector_templates', type_='foreignkey')
    op.drop_constraint(None, 'mcp_connector_templates', type_='foreignkey')
    op.drop_index(op.f('ix_mcp_connector_templates_workspace_id'), table_name='mcp_connector_templates')
    op.drop_index(op.f('ix_mcp_connector_templates_org_id'), table_name='mcp_connector_templates')
    op.drop_column('mcp_connector_templates', 'created_by_user_id')
    op.drop_column('mcp_connector_templates', 'workspace_id')
    op.drop_column('mcp_connector_templates', 'org_id')
    op.drop_column('mcp_connector_templates', 'scope')
