"""add destination columns to triggers

Revision ID: 0c41b322ea93
Revises: 76b27a2d818f
Create Date: 2026-06-23 01:26:51.666986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '0c41b322ea93'
down_revision: Union[str, Sequence[str], None] = '76b27a2d818f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'triggers',
        sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        'triggers',
        sa.Column('im_account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        'triggers',
        sa.Column('im_channel_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    )
    op.add_column(
        'triggers',
        sa.Column('im_scope_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        'triggers',
        sa.Column('im_scope_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    )
    op.create_index(
        'ix_triggers_im_channel', 'triggers', ['im_account_id', 'im_channel_id'], unique=False
    )
    op.create_index(
        op.f('ix_triggers_topic_id'), 'triggers', ['topic_id'], unique=False
    )
    op.create_foreign_key(
        'fk_triggers_im_account_id',
        'triggers',
        'im_connector_accounts',
        ['im_account_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_triggers_topic_id',
        'triggers',
        'topics',
        ['topic_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # Value-space CHECK on the discriminator. No prior CHECK exists today
    # on triggers.conversation_policy, so this is a fresh CREATE.
    op.create_check_constraint(
        "ck_triggers_conversation_policy",
        "triggers",
        "conversation_policy IN ('new_each_time', 'im_channel')",
    )
    # Minimal shape CHECK: im_channel may set im_account_id; new_each_time may not.
    op.create_check_constraint(
        "ck_triggers_target_shape",
        "triggers",
        """
        (conversation_policy = 'new_each_time' AND im_account_id IS NULL)
     OR (conversation_policy = 'im_channel')
        """,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_triggers_target_shape", "triggers", type_="check")
    op.drop_constraint("ck_triggers_conversation_policy", "triggers", type_="check")
    op.drop_constraint('fk_triggers_topic_id', 'triggers', type_='foreignkey')
    op.drop_constraint('fk_triggers_im_account_id', 'triggers', type_='foreignkey')
    op.drop_index(op.f('ix_triggers_topic_id'), table_name='triggers')
    op.drop_index('ix_triggers_im_channel', table_name='triggers')
    op.drop_column('triggers', 'im_scope_kind')
    op.drop_column('triggers', 'im_scope_key')
    op.drop_column('triggers', 'im_channel_id')
    op.drop_column('triggers', 'im_account_id')
    op.drop_column('triggers', 'topic_id')
