"""sandbox_env_drop_plain_value

Revision ID: 0c4b0b86709a
Revises: e0a411d361fb
Create Date: 2026-05-31 18:54:24.113589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '0c4b0b86709a'
down_revision: Union[str, Sequence[str], None] = 'e0a411d361fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill guard: fresh deployment has no plain-value rows, but assert just in case
    conn = op.get_bind()
    count = conn.execute(
        sa.text("SELECT COUNT(*) FROM sandbox_env_vars WHERE plain_value IS NOT NULL")
    ).scalar()
    if count:
        raise RuntimeError(
            f"Cannot migrate: {count} sandbox_env_vars row(s) still have plain_value set. "
            "Encrypt and migrate them to credential_id first."
        )

    # Drop old value-shape CHECK (references plain_value column)
    op.drop_constraint('ck_sandbox_env_value_shape', 'sandbox_env_vars', type_='check')
    # Drop the now-unused plain_value column
    op.drop_column('sandbox_env_vars', 'plain_value')
    # New CHECK: credential_id must always be present (both types use credential vault)
    op.create_check_constraint(
        'ck_sandbox_env_vars_credential_required',
        'sandbox_env_vars',
        'credential_id IS NOT NULL',
    )


def downgrade() -> None:
    op.drop_constraint('ck_sandbox_env_vars_credential_required', 'sandbox_env_vars', type_='check')
    op.add_column('sandbox_env_vars', sa.Column('plain_value', sa.String(length=4096), nullable=True))
    op.create_check_constraint(
        'ck_sandbox_env_value_shape',
        'sandbox_env_vars',
        "(is_secret AND credential_id IS NOT NULL AND plain_value IS NULL"
        " OR (NOT is_secret AND plain_value IS NOT NULL AND credential_id IS NULL"
        " AND hosts IS NULL AND header_names IS NULL))",
    )
