"""record task start attempts and foreground delivery

Revision ID: 17410d02fbaf
Revises: 0430ad3006d8
Create Date: 2026-09-21 04:43:33.051195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '17410d02fbaf'
down_revision: Union[str, Sequence[str], None] = '0430ad3006d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_tasks', sa.Column('foreground_result_delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sandbox_commands', sa.Column('start_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('sandbox_commands', sa.Column('start_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox_commands', 'start_requested_at')
    op.drop_column('sandbox_commands', 'start_token')
    op.drop_column('background_tasks', 'foreground_result_delivered_at')
    # ### end Alembic commands ###
