"""add mcp connector tables

Revision ID: 1984c75dab8d
Revises: cb2c39969ef1
Create Date: 2026-04-30 16:26:28.458181

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1984c75dab8d"
down_revision: str | Sequence[str] | None = "cb2c39969ef1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_servers",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("owner_workspace_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("server_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("server_url_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("transport", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("auth_method", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("credential_scope", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("credential_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
        sa.Column("oauth_client_config", sa.JSON(), nullable=True),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("tools_cache", sa.JSON(), nullable=True),
        sa.Column("authed", sa.Boolean(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("last_discovered_at", sa.DateTime(), nullable=True),
        sa.Column("timeout", sa.Float(), nullable=False),
        sa.Column("sse_read_timeout", sa.Float(), nullable=False),
        sa.Column(
            "created_by_user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "owner_workspace_id", "name", name="uq_mcp_server_name"),
        sa.UniqueConstraint(
            "org_id", "owner_workspace_id", "server_url_hash", name="uq_mcp_server_url"
        ),
    )
    op.create_index(op.f("ix_mcp_servers_org_id"), "mcp_servers", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_mcp_servers_owner_workspace_id"),
        "mcp_servers",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_table(
        "user_mcp_credentials",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("credential_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column(
            "oauth_refresh_token_credential_id",
            sqlmodel.sql.sqltypes.AutoString(length=36),
            nullable=True,
        ),
        sa.Column("oauth_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "mcp_server_id", name="uq_user_mcp_cred"),
    )
    op.create_index(
        op.f("ix_user_mcp_credentials_mcp_server_id"),
        "user_mcp_credentials",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_mcp_credentials_org_id"), "user_mcp_credentials", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_mcp_credentials_user_id"), "user_mcp_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "workspace_mcp_bindings",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_by_user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "mcp_server_id", name="uq_ws_mcp_binding"),
    )
    op.create_index(
        op.f("ix_workspace_mcp_bindings_mcp_server_id"),
        "workspace_mcp_bindings",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_mcp_bindings_org_id"), "workspace_mcp_bindings", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_mcp_bindings_workspace_id"),
        "workspace_mcp_bindings",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "workspace_mcp_credentials",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("credential_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column(
            "created_by_user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "mcp_server_id", name="uq_ws_mcp_cred"),
    )
    op.create_index(
        op.f("ix_workspace_mcp_credentials_mcp_server_id"),
        "workspace_mcp_credentials",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_mcp_credentials_org_id"),
        "workspace_mcp_credentials",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_mcp_credentials_workspace_id"),
        "workspace_mcp_credentials",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workspace_mcp_credentials_workspace_id"), table_name="workspace_mcp_credentials"
    )
    op.drop_index(
        op.f("ix_workspace_mcp_credentials_org_id"), table_name="workspace_mcp_credentials"
    )
    op.drop_index(
        op.f("ix_workspace_mcp_credentials_mcp_server_id"), table_name="workspace_mcp_credentials"
    )
    op.drop_table("workspace_mcp_credentials")
    op.drop_index(
        op.f("ix_workspace_mcp_bindings_workspace_id"), table_name="workspace_mcp_bindings"
    )
    op.drop_index(op.f("ix_workspace_mcp_bindings_org_id"), table_name="workspace_mcp_bindings")
    op.drop_index(
        op.f("ix_workspace_mcp_bindings_mcp_server_id"), table_name="workspace_mcp_bindings"
    )
    op.drop_table("workspace_mcp_bindings")
    op.drop_index(op.f("ix_user_mcp_credentials_user_id"), table_name="user_mcp_credentials")
    op.drop_index(op.f("ix_user_mcp_credentials_org_id"), table_name="user_mcp_credentials")
    op.drop_index(op.f("ix_user_mcp_credentials_mcp_server_id"), table_name="user_mcp_credentials")
    op.drop_table("user_mcp_credentials")
    op.drop_index(op.f("ix_mcp_servers_owner_workspace_id"), table_name="mcp_servers")
    op.drop_index(op.f("ix_mcp_servers_org_id"), table_name="mcp_servers")
    op.drop_table("mcp_servers")
    # ### end Alembic commands ###
