"""sandbox reconciler last_provider_check

Revision ID: 1f65e338699a
Revises: d38ab8f46a25
Create Date: 2026-05-28 04:00:52.208014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '1f65e338699a'
down_revision: Union[str, Sequence[str], None] = 'd38ab8f46a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sandboxes', sa.Column('last_provider_check', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_sandboxes_last_provider_check'), 'user_sandboxes', ['last_provider_check'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sandboxes_last_provider_check'), table_name='user_sandboxes')
    op.drop_column('user_sandboxes', 'last_provider_check')
    # ### end Alembic commands ###
