"""im bot settings: attributes cols, thread_link topic_id, drop im_channel_bindings

Revision ID: 2031a448c1f6
Revises: f30c90a6392f
Create Date: 2026-06-23 15:06:59.957445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2031a448c1f6'
down_revision: Union[str, Sequence[str], None] = 'f30c90a6392f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_im_channel_binding_account'), table_name='im_channel_bindings')
    op.drop_index(op.f('ix_im_channel_bindings_org_id'), table_name='im_channel_bindings')
    op.drop_index(op.f('ix_im_channel_bindings_workspace_id'), table_name='im_channel_bindings')
    op.drop_index(op.f('uq_im_channel_binding'), table_name='im_channel_bindings')
    op.drop_table('im_channel_bindings')
    op.add_column('conversations', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('im_thread_links', sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_foreign_key(
        'im_thread_links_topic_id_fkey', 'im_thread_links', 'topics', ['topic_id'], ['id']
    )
    op.add_column('topics', sa.Column('attributes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'attributes')
    op.drop_constraint('im_thread_links_topic_id_fkey', 'im_thread_links', type_='foreignkey')
    op.drop_column('im_thread_links', 'topic_id')
    op.drop_column('conversations', 'attributes')
    op.create_table('im_channel_bindings',
    sa.Column('org_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('sandbox_mode', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], name=op.f('im_channel_bindings_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('im_channel_bindings_org_id_fkey')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('im_channel_bindings_topic_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('im_channel_bindings_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('im_channel_bindings_pkey'))
    )
    op.create_index(op.f('uq_im_channel_binding'), 'im_channel_bindings', ['account_id', 'channel_id'], unique=True)
    op.create_index(op.f('ix_im_channel_bindings_workspace_id'), 'im_channel_bindings', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_im_channel_bindings_org_id'), 'im_channel_bindings', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_channel_binding_account'), 'im_channel_bindings', ['account_id'], unique=False)
    # ### end Alembic commands ###
