"""fence pending hard deletions

Revision ID: 27a5dc1bc12d
Revises: 824b22ddaa1e
Create Date: 2026-09-22 09:33:50.116376

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27a5dc1bc12d"
down_revision: str | Sequence[str] | None = "824b22ddaa1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deletion_pending_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "workspaces", sa.Column("deletion_pending_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "deletion_pending_at")
    op.drop_column("users", "deletion_pending_at")
    # ### end Alembic commands ###
