"""drop legacy model_presets rows

Revision ID: 27df13e3949d
Revises: bed4e0f0065c
Create Date: 2026-06-21 00:18:18.738947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '27df13e3949d'
down_revision: Union[str, Sequence[str], None] = '00fe892184fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop any legacy-shaped model_presets rows (clean cutover).

    The seeder now writes the tiered ModelPresetsConfig shape and the runtime
    rejects the old {presets, task_presets} shape. Delete the rows so startup
    re-seeds the system row from llm.model_presets.
    """
    op.execute("DELETE FROM org_settings WHERE key = 'model_presets'")


def downgrade() -> None:
    """No-op: legacy rows are not reconstructable."""
    pass
