"""sandbox policy null-safe partial unique indexes

Revision ID: 28c4c57516f6
Revises: 6c2c51362b70
Create Date: 2026-05-28 19:18:35.669148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '28c4c57516f6'
down_revision: Union[str, Sequence[str], None] = '6c2c51362b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_sandbox_policy_scope'), table_name='sandbox_policies')
    op.create_index('uq_sandbox_policy_org_default', 'sandbox_policies', ['org_id'], unique=True, postgresql_where=sa.text('scope_workspace_id IS NULL'), sqlite_where=sa.text('scope_workspace_id IS NULL'))
    op.create_index('uq_sandbox_policy_org_workspace', 'sandbox_policies', ['org_id', 'scope_workspace_id'], unique=True, postgresql_where=sa.text('scope_workspace_id IS NOT NULL'), sqlite_where=sa.text('scope_workspace_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sandbox_policy_org_workspace', table_name='sandbox_policies', postgresql_where=sa.text('scope_workspace_id IS NOT NULL'), sqlite_where=sa.text('scope_workspace_id IS NOT NULL'))
    op.drop_index('uq_sandbox_policy_org_default', table_name='sandbox_policies', postgresql_where=sa.text('scope_workspace_id IS NULL'), sqlite_where=sa.text('scope_workspace_id IS NULL'))
    op.create_index(op.f('uq_sandbox_policy_scope'), 'sandbox_policies', ['org_id', 'scope_workspace_id'], unique=True)
    # ### end Alembic commands ###
