"""conversations soft delete: add deleted_at

Revision ID: 2b4e5bebbc7f
Revises: 1991a15c011d
Create Date: 2026-05-13 20:06:35.591498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4e5bebbc7f'
down_revision: Union[str, Sequence[str], None] = '1991a15c011d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_column('conversations', 'deleted_at')
    # ### end Alembic commands ###
