"""sandbox policy network default action

Revision ID: 2f3d624337bd
Revises: e2dbb11407ca
Create Date: 2026-05-30 21:06:38.597068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '2f3d624337bd'
down_revision: Union[str, Sequence[str], None] = 'e2dbb11407ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox_policies', sa.Column('network_default_action', sqlmodel.sql.sqltypes.AutoString(length=10), server_default='deny', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox_policies', 'network_default_action')
    # ### end Alembic commands ###
