"""cubepi v3 to v4 runs

Revision ID: 4137c1986c3e
Revises: 060310ecfd8a
Create Date: 2026-06-07 01:13:28.185638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '4137c1986c3e'
down_revision: Union[str, Sequence[str], None] = '060310ecfd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Hand-added: cubepi v3 -> v4 schema upgrade.
    #
    # autogenerate produces an empty diff because cubepi_messages and
    # cubepi_runs (and their partitions) are listed in alembic/env.py's
    # _CHECKPOINT_TABLES / cubepi_*_p prefix guards. SQLAlchemy MetaData
    # cannot model partition DDL, so the upstream helper is the only
    # correct source of these statements.
    #
    # upgrade_v3_to_v4_op() adds:
    #   * cubepi_messages.run_id column (ADD COLUMN IF NOT EXISTS)
    #   * ix_cubepi_messages_thread_run on (thread_id, run_id) (IF NOT EXISTS)
    #   * cubepi_runs partitioned parent (IF NOT EXISTS) with
    #     FK (thread_id) -> cubepi_threads ON DELETE CASCADE
    #   * ix_cubepi_runs_thread_seq on (thread_id, completion_seq) (IF NOT EXISTS)
    #   * 64 child partitions cubepi_runs_p00..p63 (no IF NOT EXISTS on
    #     partitions; partial-failure re-runs require manual cleanup)
    from cubepi.checkpointer.postgres.alembic_helpers import (
        upgrade_v3_to_v4_op,
        write_schema_version_op,
    )

    op.execute(upgrade_v3_to_v4_op())
    op.execute(write_schema_version_op())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Hand-added: symmetric drop. DROP TABLE ... CASCADE removes child
    # partitions and the ix_cubepi_runs_thread_seq index along with the
    # cubepi_runs parent. Dropping cubepi_messages.run_id implicitly drops
    # ix_cubepi_messages_thread_run because it references the column, but
    # we DROP IF EXISTS explicitly for clarity.
    op.execute("DROP TABLE IF EXISTS cubepi_runs CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_cubepi_messages_thread_run")
    op.execute("ALTER TABLE cubepi_messages DROP COLUMN IF EXISTS run_id")
    op.execute(
        "DELETE FROM cubepi_schema_version WHERE version <> 3; "
        "INSERT INTO cubepi_schema_version (version) VALUES (3) "
        "ON CONFLICT DO NOTHING;"
    )
