"""persist scheduled execution handoff

Revision ID: 4450140cb24b
Revises: 725935256835
Create Date: 2026-09-22 07:00:20.135105

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4450140cb24b"
down_revision: str | Sequence[str] | None = "725935256835"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "im_run_queue", sa.Column("execution_admission_id", sa.String(length=20), nullable=True)
    )
    op.create_foreign_key(
        "fk_im_run_queue_execution_admission_id",
        "im_run_queue",
        "conversation_execution_admissions",
        ["execution_admission_id"],
        ["id"],
    )
    op.add_column("scheduled_task_runs", sa.Column("execution_snapshot", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduled_task_runs", "execution_snapshot")
    op.drop_constraint("fk_im_run_queue_execution_admission_id", "im_run_queue", type_="foreignkey")
    op.drop_column("im_run_queue", "execution_admission_id")
    # ### end Alembic commands ###
