"""mcp template+install static auth style fields

Revision ID: 49844ea5ac7b
Revises: 6c69cc288404
Create Date: 2026-05-28 02:44:08.770820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '49844ea5ac7b'
down_revision: Union[str, Sequence[str], None] = '6c69cc288404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connector_installs', sa.Column('static_auth_style', sqlmodel.sql.sqltypes.AutoString(length=16), server_default=sa.text("'bearer'"), nullable=False))
    op.add_column('mcp_connector_installs', sa.Column('static_auth_header_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('mcp_connector_installs', sa.Column('static_auth_query_param', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('mcp_connector_templates', sa.Column('static_auth_style', sqlmodel.sql.sqltypes.AutoString(length=16), server_default=sa.text("'bearer'"), nullable=False))
    op.add_column('mcp_connector_templates', sa.Column('static_auth_header_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('mcp_connector_templates', sa.Column('static_auth_query_param', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_connector_templates', 'static_auth_query_param')
    op.drop_column('mcp_connector_templates', 'static_auth_header_name')
    op.drop_column('mcp_connector_templates', 'static_auth_style')
    op.drop_column('mcp_connector_installs', 'static_auth_query_param')
    op.drop_column('mcp_connector_installs', 'static_auth_header_name')
    op.drop_column('mcp_connector_installs', 'static_auth_style')
    # ### end Alembic commands ###
