"""conversation has_messages

Revision ID: 49ec26f0f17c
Revises: 70b67e12643b
Create Date: 2026-05-04 22:57:11.869879

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49ec26f0f17c"
down_revision: str | Sequence[str] | None = "70b67e12643b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "has_messages",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_index(
        op.f("ix_conversations_has_messages"),
        "conversations",
        ["has_messages"],
        unique=False,
    )
    # Backfill: any conversation that already has activity (updated_at drifted
    # from created_at) is treated as having messages.
    op.execute(
        "UPDATE conversations SET has_messages = TRUE "
        "WHERE updated_at > created_at + INTERVAL '1 second'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_has_messages"), table_name="conversations")
    op.drop_column("conversations", "has_messages")
    # ### end Alembic commands ###
