"""add egress_proxy to sandbox_policies

Revision ID: 4b2f76fe406d
Revises: 0c4b0b86709a
Create Date: 2026-06-02 00:04:31.720327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '4b2f76fe406d'
down_revision: Union[str, Sequence[str], None] = '0c4b0b86709a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox_policies', sa.Column('egress_proxy', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox_policies', 'egress_proxy')
    # ### end Alembic commands ###
