"""conversation delete cascade: cascade artifacts/versions, set null on billing_events

Revision ID: 4ee06307776d
Revises: 1991a15c011d
Create Date: 2026-05-13 19:28:55.141261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee06307776d'
down_revision: Union[str, Sequence[str], None] = '1991a15c011d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artifact_versions_artifact_id_fkey'), 'artifact_versions', type_='foreignkey')
    op.create_foreign_key('artifact_versions_artifact_id_fkey', 'artifact_versions', 'artifacts', ['artifact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('artifacts_conversation_id_fkey'), 'artifacts', type_='foreignkey')
    op.create_foreign_key('artifacts_conversation_id_fkey', 'artifacts', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('billing_events', 'conversation_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('billing_events_conversation_id_fkey'), 'billing_events', type_='foreignkey')
    op.create_foreign_key('billing_events_conversation_id_fkey', 'billing_events', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_events_conversation_id_fkey', 'billing_events', type_='foreignkey')
    op.create_foreign_key(op.f('billing_events_conversation_id_fkey'), 'billing_events', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('billing_events', 'conversation_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('artifacts_conversation_id_fkey', 'artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('artifacts_conversation_id_fkey'), 'artifacts', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint('artifact_versions_artifact_id_fkey', 'artifact_versions', type_='foreignkey')
    op.create_foreign_key(op.f('artifact_versions_artifact_id_fkey'), 'artifact_versions', 'artifacts', ['artifact_id'], ['id'])
    # ### end Alembic commands ###
