"""scope steering cancellation by source and generation

Revision ID: 51680dae2417
Revises: 53dfe7ed4449
Create Date: 2026-09-21 23:13:47.088876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '51680dae2417'
down_revision: Union[str, Sequence[str], None] = '53dfe7ed4449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steering_messages', sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(length=32), server_default='user_message', nullable=False))
    op.add_column('steering_messages', sa.Column('execution_generation', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steering_messages', 'execution_generation')
    op.drop_column('steering_messages', 'source_kind')
    # ### end Alembic commands ###
