"""persist background notice input source

Revision ID: 53f232b2bc4d
Revises: 27a5dc1bc12d
Create Date: 2026-09-22 11:57:29.533509

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53f232b2bc4d"
down_revision: str | Sequence[str] | None = "27a5dc1bc12d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("steering_messages", sa.Column("notice_id", sa.String(length=20), nullable=True))
    op.create_index(
        "uq_steering_messages_conversation_notice_id",
        "steering_messages",
        ["conversation_id", "notice_id"],
        unique=True,
    )
    op.create_foreign_key(
        "steering_messages_notice_id_fkey",
        "steering_messages",
        "background_task_events",
        ["notice_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("steering_messages_notice_id_fkey", "steering_messages", type_="foreignkey")
    op.drop_index("uq_steering_messages_conversation_notice_id", table_name="steering_messages")
    op.drop_column("steering_messages", "notice_id")
    # ### end Alembic commands ###
