"""add cubepi checkpointer tables

Revision ID: 555c11215b57
Revises: 4be6ed892e02
Create Date: 2026-05-13 11:36:24.961848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555c11215b57'
down_revision: Union[str, Sequence[str], None] = '4be6ed892e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubepi_schema_version',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('cubepi_threads',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('parent_thread_id', sa.Text(), nullable=True),
    sa.Column('forked_at_seq', sa.BigInteger(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_thread_id'], ['cubepi_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('cubepi_messages',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['cubepi_threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'seq'),
    postgresql_partition_by='HASH (thread_id)'
    )
    op.create_index('ix_cubepi_messages_metadata_gin', 'cubepi_messages', ['metadata'], unique=False, postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    # ### end Alembic commands ###

    # Create child partitions and write schema version row
    from cubepi.checkpointer.postgres.alembic_helpers import (
        create_message_partitions_op,
        write_schema_version_op,
    )

    op.execute(create_message_partitions_op())
    op.execute(write_schema_version_op())


def downgrade() -> None:
    """Downgrade schema."""
    # Drop 64 child partitions before parent (modulus is fixed at 64 for this migration)
    for i in range(64):
        op.execute(f"DROP TABLE IF EXISTS cubepi_messages_p{i:02d}")
    op.drop_index('ix_cubepi_messages_metadata_gin', table_name='cubepi_messages', postgresql_using='gin', postgresql_ops={'metadata': 'jsonb_path_ops'})
    op.drop_table('cubepi_schema_version')
    op.drop_table('cubepi_messages')
    op.drop_table('cubepi_threads')
