"""sandbox entity persistence

Revision ID: 66c3b3dfdec3
Revises: 74a3486fa05d
Create Date: 2026-06-27 10:46:58.152049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '66c3b3dfdec3'
down_revision: Union[str, Sequence[str], None] = '74a3486fa05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sandboxes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_sandboxes', 'sandbox_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

    # Hand-written: alembic can't detect postgresql_where changes on indexes,
    # so autogen skipped the index from `WHERE status IN ('provisioning','running')`
    # to `WHERE deleted_at IS NULL`.
    op.drop_index('uq_user_sandbox_active_scope', table_name='user_sandboxes')
    op.create_index(
        'uq_user_sandbox_active_scope',
        'user_sandboxes',
        ['org_id', 'workspace_id', 'scope_type', 'scope_id'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )

    # Data migration: stamp terminated sandboxes as deleted
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE user_sandboxes SET deleted_at = updated_at "
            "WHERE status = 'terminated'"
        )
    )
    conn.execute(
        sa.text(
            "UPDATE user_sandboxes SET deleted_at = now(), status = 'terminated', sandbox_id = NULL "
            "WHERE scope_type IN ('topic', 'conversation') AND deleted_at IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sandboxes', 'sandbox_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_sandboxes', 'deleted_at')
    # ### end Alembic commands ###

    # Hand-written: restore the old status-based partial index.
    # Postgres auto-drops the `deleted_at IS NULL` index when the column
    # is dropped above, so only the CREATE is needed.
    op.create_index(
        'uq_user_sandbox_active_scope',
        'user_sandboxes',
        ['org_id', 'workspace_id', 'scope_type', 'scope_id'],
        unique=True,
        postgresql_where=sa.text(
            "status::text = ANY (ARRAY['provisioning'::character varying, 'running'::character varying]::text[])"
        ),
    )
