"""sandbox policies and active unique index

Revision ID: 6c2c51362b70
Revises: 6c69cc288404
Create Date: 2026-05-28 09:39:04.938113

Assumes clean data: no (org_id, workspace_id, user_id) duplicate rows in
status IN ('provisioning','running'). The project has not shipped publicly,
so this is a safe assumption. If a real deployment ever hits dirty data,
operators run a one-off cleanup script before applying this migration;
that is NOT migration logic.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '6c2c51362b70'
# Re-parented onto the post-#145/#150/#152 head after rebasing #144 onto main —
# keeps the alembic chain linear (no parallel heads). The migration ops
# themselves are independent of #145/#150/#152 (new table + new partial
# index over user_sandboxes columns that already existed pre-#144).
down_revision: Union[str, Sequence[str], None] = 'ea209f51b410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_policies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scope_workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('default_image', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('network_rules', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('command_rules', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scope_workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_policies_org_id'), 'sandbox_policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_sandbox_policies_scope_workspace_id'), 'sandbox_policies', ['scope_workspace_id'], unique=False)
    op.create_index('uq_sandbox_policy_scope', 'sandbox_policies', ['org_id', 'scope_workspace_id'], unique=True)
    op.create_index('uq_user_sandbox_active', 'user_sandboxes', ['org_id', 'workspace_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_sandbox_active', table_name='user_sandboxes', postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))
    op.drop_index('uq_sandbox_policy_scope', table_name='sandbox_policies')
    op.drop_index(op.f('ix_sandbox_policies_scope_workspace_id'), table_name='sandbox_policies')
    op.drop_index(op.f('ix_sandbox_policies_org_id'), table_name='sandbox_policies')
    op.drop_table('sandbox_policies')
    # ### end Alembic commands ###
