"""conversation model_key + thinking

Revision ID: 7007881c1f6f
Revises: 27df13e3949d
Create Date: 2026-06-21 12:36:15.699629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '7007881c1f6f'
down_revision: Union[str, Sequence[str], None] = '27df13e3949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('model_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('conversations', sa.Column('thinking', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'thinking')
    op.drop_column('conversations', 'model_key')
    # ### end Alembic commands ###
