"""add provider model management tables

Revision ID: 70b67e12643b
Revises: 1984c75dab8d
Create Date: 2026-05-01 05:40:00.324393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 (used by autogenerated AutoString references)


# revision identifiers, used by Alembic.
revision: str = '70b67e12643b'
down_revision: Union[str, Sequence[str], None] = '1984c75dab8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('reasoning', sa.Boolean(), nullable=False),
    sa.Column('input_modalities', sa.JSON(), nullable=True),
    sa.Column('cost_input', sa.Float(), nullable=False),
    sa.Column('cost_output', sa.Float(), nullable=False),
    sa.Column('cost_cache_read', sa.Float(), nullable=False),
    sa.Column('cost_cache_write', sa.Float(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('extra_body', sa.JSON(), nullable=True),
    sa.Column('extra_headers', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_model_provider_model')
    )
    op.create_index(op.f('ix_models_org_id'), 'models', ['org_id'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_table('org_provider_overrides',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider_id', name='uq_org_provider_override')
    )
    op.create_index(op.f('ix_org_provider_overrides_org_id'), 'org_provider_overrides', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_provider_overrides_provider_id'), 'org_provider_overrides', ['provider_id'], unique=False)
    op.create_table('org_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_org_settings_org_key')
    )
    op.create_index(op.f('ix_org_settings_org_id'), 'org_settings', ['org_id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('oauth_client_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('oauth_client_secret', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('oauth_auth_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('oauth_token_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('extra_body', sa.JSON(), nullable=True),
    sa.Column('extra_headers', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_provider_org_name')
    )
    op.create_index(op.f('ix_providers_org_id'), 'providers', ['org_id'], unique=False)
    op.create_index(
        'uq_provider_system_name',
        'providers',
        ['name'],
        unique=True,
        postgresql_where=sa.text('org_id IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_provider_system_name', table_name='providers', postgresql_where=sa.text('org_id IS NULL'))
    op.drop_index(op.f('ix_providers_org_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_org_settings_org_id'), table_name='org_settings')
    op.drop_table('org_settings')
    op.drop_index(op.f('ix_org_provider_overrides_provider_id'), table_name='org_provider_overrides')
    op.drop_index(op.f('ix_org_provider_overrides_org_id'), table_name='org_provider_overrides')
    op.drop_table('org_provider_overrides')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_org_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
