"""freeze im queue actor

Revision ID: 725935256835
Revises: 7bf776207fc1
Create Date: 2026-09-22 06:42:04.132281

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "725935256835"
down_revision: str | Sequence[str] | None = "7bf776207fc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("im_run_queue", sa.Column("actor_user_id", sa.String(length=20), nullable=True))
    op.create_foreign_key(
        "fk_im_run_queue_actor_user_id_users", "im_run_queue", "users", ["actor_user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_im_run_queue_actor_user_id_users", "im_run_queue", type_="foreignkey")
    op.drop_column("im_run_queue", "actor_user_id")
    # ### end Alembic commands ###
