"""add steering messages

Revision ID: 72d48703ca92
Revises: acacbbde0622
Create Date: 2026-08-12 09:06:31.965226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '72d48703ca92'
down_revision: Union[str, Sequence[str], None] = 'acacbbde0622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steering_messages',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('client_steer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sender_display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hitl_question_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('delivery_owner', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('delivery_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steering_messages_org_id'), 'steering_messages', ['org_id'], unique=False)
    op.create_index('ix_steering_messages_org_ws', 'steering_messages', ['org_id', 'workspace_id'], unique=False)
    op.create_index('ix_steering_messages_run_delivery', 'steering_messages', ['run_id', 'state', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_steering_messages_workspace_id'), 'steering_messages', ['workspace_id'], unique=False)
    op.create_index('uq_steering_messages_conversation_client_id', 'steering_messages', ['conversation_id', 'client_steer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_steering_messages_conversation_client_id', table_name='steering_messages')
    op.drop_index(op.f('ix_steering_messages_workspace_id'), table_name='steering_messages')
    op.drop_index('ix_steering_messages_run_delivery', table_name='steering_messages')
    op.drop_index('ix_steering_messages_org_ws', table_name='steering_messages')
    op.drop_index(op.f('ix_steering_messages_org_id'), table_name='steering_messages')
    op.drop_table('steering_messages')
    # ### end Alembic commands ###
