"""add sandbox sync observability

Revision ID: 74a3486fa05d
Revises: 7aec44dafed6
Create Date: 2026-06-26 12:20:47.017601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '74a3486fa05d'
down_revision: Union[str, Sequence[str], None] = '7aec44dafed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sandbox_sync_events',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_sandbox_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('manifest_snapshot', sa.JSON(), nullable=True),
    sa.Column('n_pushed', sa.Integer(), nullable=False),
    sa.Column('n_removed', sa.Integer(), nullable=False),
    sa.Column('tar_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_sandbox_id'], ['user_sandboxes.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sandbox_sync_events_org_id'), 'user_sandbox_sync_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_sandbox_sync_events_user_sandbox_id'), 'user_sandbox_sync_events', ['user_sandbox_id'], unique=False)
    op.create_index(op.f('ix_user_sandbox_sync_events_workspace_id'), 'user_sandbox_sync_events', ['workspace_id'], unique=False)
    op.create_index('ix_uss_org_ws_started', 'user_sandbox_sync_events', ['org_id', 'workspace_id', 'started_at'], unique=False)
    op.create_index('ix_uss_sandbox_started', 'user_sandbox_sync_events', ['user_sandbox_id', 'started_at'], unique=False)
    op.add_column('user_sandboxes', sa.Column('skills_manifest_hash', sqlmodel.sql.sqltypes.AutoString(length=71), nullable=True))
    op.add_column('user_sandboxes', sa.Column('skills_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_sandboxes', sa.Column('last_skill_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sandboxes', sa.Column('last_skill_sync_event_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_foreign_key(None, 'user_sandboxes', 'user_sandbox_sync_events', ['last_skill_sync_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sandboxes', type_='foreignkey')
    op.drop_column('user_sandboxes', 'last_skill_sync_event_id')
    op.drop_column('user_sandboxes', 'last_skill_sync_at')
    op.drop_column('user_sandboxes', 'skills_count')
    op.drop_column('user_sandboxes', 'skills_manifest_hash')
    op.drop_index('ix_uss_sandbox_started', table_name='user_sandbox_sync_events')
    op.drop_index('ix_uss_org_ws_started', table_name='user_sandbox_sync_events')
    op.drop_index(op.f('ix_user_sandbox_sync_events_workspace_id'), table_name='user_sandbox_sync_events')
    op.drop_index(op.f('ix_user_sandbox_sync_events_user_sandbox_id'), table_name='user_sandbox_sync_events')
    op.drop_index(op.f('ix_user_sandbox_sync_events_org_id'), table_name='user_sandbox_sync_events')
    op.drop_table('user_sandbox_sync_events')
    # ### end Alembic commands ###
