"""track sandbox cleanup requests

Revision ID: 76a2d219d682
Revises: 53f232b2bc4d
Create Date: 2026-09-22 20:25:40.495255

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76a2d219d682"
down_revision: str | Sequence[str] | None = "53f232b2bc4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sandboxes",
        sa.Column("cleanup_action", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    )
    op.add_column(
        "user_sandboxes",
        sa.Column("cleanup_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sandboxes", "cleanup_requested_at")
    op.drop_column("user_sandboxes", "cleanup_action")
    # ### end Alembic commands ###
