"""add destination columns to scheduled_tasks

Revision ID: 76b27a2d818f
Revises: 7007881c1f6f
Create Date: 2026-06-23 01:25:01.270386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '76b27a2d818f'
down_revision: Union[str, Sequence[str], None] = '7007881c1f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'scheduled_tasks',
        sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        'scheduled_tasks',
        sa.Column('im_account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        'scheduled_tasks',
        sa.Column('im_channel_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    )
    op.add_column(
        'scheduled_tasks',
        sa.Column('im_scope_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        'scheduled_tasks',
        sa.Column('im_scope_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    )
    op.create_index(
        op.f('ix_scheduled_tasks_topic_id'), 'scheduled_tasks', ['topic_id'], unique=False
    )
    op.create_foreign_key(
        'fk_scheduled_tasks_im_account_id',
        'scheduled_tasks',
        'im_connector_accounts',
        ['im_account_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_scheduled_tasks_topic_id',
        'scheduled_tasks',
        'topics',
        ['topic_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # Value-space CHECK on the discriminator. No prior CHECK exists today,
    # so this is a fresh CREATE (no drop_constraint at the top).
    op.create_check_constraint(
        "ck_scheduled_tasks_target_mode",
        "scheduled_tasks",
        "target_mode IN ('fixed', 'new_each_run', 'im_channel')",
    )
    # Minimal shape CHECK: ensures the destination columns match the mode.
    op.create_check_constraint(
        "ck_scheduled_tasks_target_shape",
        "scheduled_tasks",
        """
        (target_mode = 'fixed'        AND target_conversation_id IS NOT NULL
                                      AND im_account_id IS NULL)
     OR (target_mode = 'new_each_run' AND target_conversation_id IS NULL
                                      AND im_account_id IS NULL)
     OR (target_mode = 'im_channel'   AND target_conversation_id IS NULL)
        """,
    )
    op.create_index(
        "ix_scheduled_tasks_im_channel",
        "scheduled_tasks",
        ["im_account_id", "im_channel_id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_scheduled_tasks_im_channel", table_name="scheduled_tasks")
    op.drop_constraint("ck_scheduled_tasks_target_shape", "scheduled_tasks", type_="check")
    op.drop_constraint("ck_scheduled_tasks_target_mode", "scheduled_tasks", type_="check")
    op.drop_constraint('fk_scheduled_tasks_topic_id', 'scheduled_tasks', type_='foreignkey')
    op.drop_constraint('fk_scheduled_tasks_im_account_id', 'scheduled_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_tasks_topic_id'), table_name='scheduled_tasks')
    op.drop_column('scheduled_tasks', 'im_scope_kind')
    op.drop_column('scheduled_tasks', 'im_scope_key')
    op.drop_column('scheduled_tasks', 'im_channel_id')
    op.drop_column('scheduled_tasks', 'im_account_id')
    op.drop_column('scheduled_tasks', 'topic_id')
