"""add content_hash to skill_versions

Revision ID: 7aec44dafed6
Revises: d1f37c369298
Create Date: 2026-06-25 15:56:02.456399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '7aec44dafed6'
down_revision: Union[str, Sequence[str], None] = 'd1f37c369298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_versions', sa.Column('content_hash', sa.String(length=71), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_versions', 'content_hash')
    # ### end Alembic commands ###
