"""add mcp connectors

Revision ID: 7bcaf228a12e
Revises: 5f7a2c1d9b40
Create Date: 2026-07-07 21:07:46.537439

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bcaf228a12e"
down_revision: str | Sequence[str] | None = "5f7a2c1d9b40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_connectors",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("template_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "slug_name", sa.String(length=72), server_default=sa.text("'mcp'"), nullable=False
        ),
        sa.Column("server_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("server_url_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("transport", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("auth_method", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("oauth_client_config", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "static_auth_style",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            server_default=sa.text("'bearer'"),
            nullable=False,
        ),
        sa.Column(
            "static_auth_header_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "static_auth_query_param", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("tools_cache", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("tool_citations", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("discovery_status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.CheckConstraint(
            "auth_method IN ('oauth','static','none')", name="ck_mcp_connectors_auth_method"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["mcp_connector_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mcp_connectors_org_id"), "mcp_connectors", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_mcp_connectors_template_id"), "mcp_connectors", ["template_id"], unique=False
    )
    op.create_index(
        "uq_mcp_connector_slug_per_org",
        "mcp_connectors",
        ["org_id", "slug_name"],
        unique=True,
        postgresql_where="status = 'active'",
    )
    op.create_index(
        "uq_mcp_connector_template_per_org",
        "mcp_connectors",
        ["org_id", "template_id"],
        unique=True,
        postgresql_where="status = 'active' AND template_id IS NOT NULL",
    )
    op.create_index(
        "uq_mcp_connector_url_per_org",
        "mcp_connectors",
        ["org_id", "server_url_hash"],
        unique=True,
        postgresql_where="status = 'active'",
    )
    op.add_column(
        "mcp_credential_grants",
        sa.Column("connector_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.create_index(
        op.f("ix_mcp_credential_grants_connector_id"),
        "mcp_credential_grants",
        ["connector_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_mcp_credential_grants_connector_id",
        "mcp_credential_grants",
        "mcp_connectors",
        ["connector_id"],
        ["id"],
    )
    op.add_column(
        "mcp_workspace_connector_states",
        sa.Column("connector_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.create_index(
        op.f("ix_mcp_workspace_connector_states_connector_id"),
        "mcp_workspace_connector_states",
        ["connector_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_mcp_workspace_connector_states_connector_id",
        "mcp_workspace_connector_states",
        "mcp_connectors",
        ["connector_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_mcp_workspace_connector_states_connector_id",
        "mcp_workspace_connector_states",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_mcp_workspace_connector_states_connector_id"),
        table_name="mcp_workspace_connector_states",
    )
    op.drop_column("mcp_workspace_connector_states", "connector_id")
    op.drop_constraint(
        "fk_mcp_credential_grants_connector_id", "mcp_credential_grants", type_="foreignkey"
    )
    op.drop_index(op.f("ix_mcp_credential_grants_connector_id"), table_name="mcp_credential_grants")
    op.drop_column("mcp_credential_grants", "connector_id")
    op.drop_index(
        "uq_mcp_connector_url_per_org",
        table_name="mcp_connectors",
        postgresql_where="status = 'active'",
    )
    op.drop_index(
        "uq_mcp_connector_template_per_org",
        table_name="mcp_connectors",
        postgresql_where="status = 'active' AND template_id IS NOT NULL",
    )
    op.drop_index(
        "uq_mcp_connector_slug_per_org",
        table_name="mcp_connectors",
        postgresql_where="status = 'active'",
    )
    op.drop_index(op.f("ix_mcp_connectors_template_id"), table_name="mcp_connectors")
    op.drop_index(op.f("ix_mcp_connectors_org_id"), table_name="mcp_connectors")
    op.drop_table("mcp_connectors")
    # ### end Alembic commands ###
