"""allow active run steering inputs

Revision ID: 7bf776207fc1
Revises: 46bded5a700f
Create Date: 2026-09-22 06:11:57.315418

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bf776207fc1"
down_revision: str | Sequence[str] | None = "46bded5a700f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "steering_messages", "hitl_question_id", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "steering_messages",
        "hitl_question_id",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    # ### end Alembic commands ###
