"""separate run start intent from worker receipt

Revision ID: 805e0dd3e385
Revises: 06bb443b55ea
Create Date: 2026-09-21 06:55:14.400214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '805e0dd3e385'
down_revision: Union[str, Sequence[str], None] = '06bb443b55ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_execution_admissions', sa.Column('run_start_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_execution_admissions', 'run_start_requested_at')
    # ### end Alembic commands ###
