"""utc timestamps

Revision ID: 8cec37bd8ee2
Revises: f3ee19317f6e
Create Date: 2026-05-29 16:35:01.666600

This migration switches all cubeplex datetime columns from
``timestamp without time zone`` to ``timestamp with time zone``.

Hand-edit: every ``op.alter_column`` call carries a manually-added
``postgresql_using="<col> AT TIME ZONE 'UTC'"`` parameter. Autogen omits
it, which would default Postgres to ``USING column::timestamptz`` -- that
interprets the naive clock value as session local time, drifting all
stored timestamps by the session ``TimeZone`` offset. Our stored values
are UTC clocks, so ``AT TIME ZONE 'UTC'`` is the correct cast.

See ``docs/dev/specs/2026-05-28-utc-timestamps-design.md`` section 3.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cec37bd8ee2'
down_revision: Union[str, Sequence[str], None] = 'f3ee19317f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifact_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifact_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('attachments', 'attached_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="attached_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('billing_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_events', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_events', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_llm_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('conversations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('egress_refs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('egress_refs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('egress_refs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('invite_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mcp_connector_installs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_installs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_installs', 'last_discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_discovered_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mcp_connector_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_credential_grants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_credential_grants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_credential_grants', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mcp_workspace_connector_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_workspace_connector_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('memory_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memory_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memory_items', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('models', 'last_test_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_test_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_preinstalled_tombstones', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_preinstalled_tombstones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_preinstalled_tombstones', 'hidden_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="hidden_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_skill_installs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_skill_installs', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="installed_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organization_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('providers', 'last_liveness_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_liveness_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sandbox_env_vars', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_env_vars', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="claimed_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_task_runs', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="next_retry_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'run_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="run_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'next_fire_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="next_fire_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'last_fired_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_fired_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('skill_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skills', 'deprecated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deprecated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('trigger_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('trigger_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('trigger_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="occurred_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('trigger_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="received_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('triggers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('triggers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('triggers', 'previous_secret_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="previous_secret_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sandboxes', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_activity_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'paused_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="paused_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'last_resumed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_resumed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'in_use_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="in_use_until AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'last_provider_check',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_provider_check AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_skill_bindings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_skill_bindings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'last_provider_check',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_provider_check AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'in_use_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="in_use_until AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'last_resumed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_resumed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'paused_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="paused_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_sandboxes', 'last_activity_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_activity_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sandboxes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('triggers', 'previous_secret_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="previous_secret_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('triggers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('triggers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('trigger_events', 'received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="received_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('trigger_events', 'occurred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="occurred_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('trigger_events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('trigger_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skills', 'deprecated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deprecated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('skills', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skills', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_versions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('skill_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_sources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('skill_sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'last_fired_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_fired_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'next_fire_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="next_fire_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'run_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="run_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'next_retry_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="next_retry_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_task_runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scheduled_task_runs', 'claimed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="claimed_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'scheduled_for',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('scheduled_task_runs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_policies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_policies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_env_vars', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('sandbox_env_vars', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('providers', 'last_liveness_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_liveness_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('providers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('providers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organization_memberships', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_memberships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_skill_installs', 'installed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="installed_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_skill_installs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'hidden_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="hidden_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('org_preinstalled_tombstones', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'last_test_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_test_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('models', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('models', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memory_items', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('memory_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memory_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('memberships', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('memberships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_workspace_connector_states', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_workspace_connector_states', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_credential_grants', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mcp_credential_grants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_credential_grants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_installs', 'last_discovered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_discovered_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mcp_connector_installs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mcp_connector_installs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('invite_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('egress_refs', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('egress_refs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('egress_refs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('credentials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('credentials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('conversations', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_llm_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_events', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_events', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('billing_events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('attachments', 'attached_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="attached_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('attachments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('attachments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifacts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifacts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('artifact_versions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    op.alter_column('artifact_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('agent_configs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('agent_configs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
