"""im connectors tables

Revision ID: 9ccd63170399
Revises: fabe1279b9f6
Create Date: 2026-06-13 12:46:37.253184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '9ccd63170399'
down_revision: Union[str, Sequence[str], None] = 'fabe1279b9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_connector_accounts',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('external_account_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('acting_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('delivery_mode', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['acting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_im_accounts_org_ws', 'im_connector_accounts', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_im_connector_accounts_org_id'), 'im_connector_accounts', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_connector_accounts_workspace_id'), 'im_connector_accounts', ['workspace_id'], unique=False)
    op.create_index('uq_im_account_platform_external', 'im_connector_accounts', ['platform', 'external_account_id'], unique=True)
    op.create_table('im_identity_links',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('im_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_im_identity_links_account_id'), 'im_identity_links', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_identity_links_org_id'), 'im_identity_links', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_identity_links_workspace_id'), 'im_identity_links', ['workspace_id'], unique=False)
    op.create_index('uq_im_identity_link', 'im_identity_links', ['account_id', 'im_user_id'], unique=True)
    op.create_table('im_thread_links',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('scope_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scope_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_im_thread_links_account_id'), 'im_thread_links', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_thread_links_conversation_id'), 'im_thread_links', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_im_thread_links_org_id'), 'im_thread_links', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_thread_links_workspace_id'), 'im_thread_links', ['workspace_id'], unique=False)
    op.create_index('uq_im_scope_link', 'im_thread_links', ['account_id', 'channel_id', 'scope_key'], unique=True)
    op.create_table('im_webhook_receipts',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('platform_event_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_im_webhook_receipts_account_id'), 'im_webhook_receipts', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_webhook_receipts_org_id'), 'im_webhook_receipts', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_webhook_receipts_workspace_id'), 'im_webhook_receipts', ['workspace_id'], unique=False)
    op.create_index('uq_im_receipt_account_event', 'im_webhook_receipts', ['account_id', 'platform_event_id'], unique=True)
    op.create_table('im_run_queue',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('receipt_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('scope_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scope_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reply_to_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('inbound_message_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('sender_im_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['im_webhook_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_im_run_queue_account_id'), 'im_run_queue', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_run_queue_org_id'), 'im_run_queue', ['org_id'], unique=False)
    op.create_index('ix_im_run_queue_pending', 'im_run_queue', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_im_run_queue_receipt_id'), 'im_run_queue', ['receipt_id'], unique=False)
    op.create_index('ix_im_run_queue_started_lease', 'im_run_queue', ['status', 'claim_lease_expires_at'], unique=False, postgresql_where=sa.text("status = 'started'"))
    op.create_index(op.f('ix_im_run_queue_workspace_id'), 'im_run_queue', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_im_run_queue_workspace_id'), table_name='im_run_queue')
    op.drop_index('ix_im_run_queue_started_lease', table_name='im_run_queue', postgresql_where=sa.text("status = 'started'"))
    op.drop_index(op.f('ix_im_run_queue_receipt_id'), table_name='im_run_queue')
    op.drop_index('ix_im_run_queue_pending', table_name='im_run_queue', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_im_run_queue_org_id'), table_name='im_run_queue')
    op.drop_index(op.f('ix_im_run_queue_account_id'), table_name='im_run_queue')
    op.drop_table('im_run_queue')
    op.drop_index('uq_im_receipt_account_event', table_name='im_webhook_receipts')
    op.drop_index(op.f('ix_im_webhook_receipts_workspace_id'), table_name='im_webhook_receipts')
    op.drop_index(op.f('ix_im_webhook_receipts_org_id'), table_name='im_webhook_receipts')
    op.drop_index(op.f('ix_im_webhook_receipts_account_id'), table_name='im_webhook_receipts')
    op.drop_table('im_webhook_receipts')
    op.drop_index('uq_im_scope_link', table_name='im_thread_links')
    op.drop_index(op.f('ix_im_thread_links_workspace_id'), table_name='im_thread_links')
    op.drop_index(op.f('ix_im_thread_links_org_id'), table_name='im_thread_links')
    op.drop_index(op.f('ix_im_thread_links_conversation_id'), table_name='im_thread_links')
    op.drop_index(op.f('ix_im_thread_links_account_id'), table_name='im_thread_links')
    op.drop_table('im_thread_links')
    op.drop_index('uq_im_identity_link', table_name='im_identity_links')
    op.drop_index(op.f('ix_im_identity_links_workspace_id'), table_name='im_identity_links')
    op.drop_index(op.f('ix_im_identity_links_org_id'), table_name='im_identity_links')
    op.drop_index(op.f('ix_im_identity_links_account_id'), table_name='im_identity_links')
    op.drop_table('im_identity_links')
    op.drop_index('uq_im_account_platform_external', table_name='im_connector_accounts')
    op.drop_index(op.f('ix_im_connector_accounts_workspace_id'), table_name='im_connector_accounts')
    op.drop_index(op.f('ix_im_connector_accounts_org_id'), table_name='im_connector_accounts')
    op.drop_index('ix_im_accounts_org_ws', table_name='im_connector_accounts')
    op.drop_table('im_connector_accounts')
    # ### end Alembic commands ###
