"""add resource limits to sandbox policies

Revision ID: 9d6af066fe66
Revises: 2031a448c1f6
Create Date: 2026-06-24 15:22:50.837781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '9d6af066fe66'
down_revision: Union[str, Sequence[str], None] = '2031a448c1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox_policies', sa.Column('resource_cpu', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('sandbox_policies', sa.Column('resource_memory', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('sandbox_policies', sa.Column('storage', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox_policies', 'storage')
    op.drop_column('sandbox_policies', 'resource_memory')
    op.drop_column('sandbox_policies', 'resource_cpu')
    # ### end Alembic commands ###
