"""drop dead skill_ids/mcp_server_ids from agent_configs

Revision ID: a2c0009ea3ad
Revises: bfd800fb39e1
Create Date: 2026-05-07 09:50:53.463310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2c0009ea3ad'
down_revision: Union[str, Sequence[str], None] = 'bfd800fb39e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'skill_ids')
    op.drop_column('agent_configs', 'mcp_server_ids')
    op.create_index(op.f('ix_org_skill_installs_workspace_id'), 'org_skill_installs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_skill_installs_workspace_id'), table_name='org_skill_installs')
    op.add_column('agent_configs', sa.Column('mcp_server_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_configs', sa.Column('skill_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
