"""drop mcp connector installs

Revision ID: a687284a937b
Revises: bdf4b31f91d2
Create Date: 2026-07-08 06:14:35.621770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a687284a937b'
down_revision: Union[str, Sequence[str], None] = 'bdf4b31f91d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connectors', sa.Column('default_credential_policy', sqlmodel.sql.sqltypes.AutoString(length=16), server_default=sa.text("'org'"), nullable=False))
    op.add_column('mcp_connectors', sa.Column('auth_status', sqlmodel.sql.sqltypes.AutoString(length=16), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('mcp_connectors', sa.Column('headers', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('mcp_connectors', sa.Column('discovery_metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('mcp_connectors', sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_connectors', sa.Column('timeout', sa.Float(), server_default=sa.text('30.0'), nullable=False))
    op.add_column('mcp_connectors', sa.Column('sse_read_timeout', sa.Float(), server_default=sa.text('300.0'), nullable=False))
    op.add_column('mcp_connectors', sa.Column('auto_enroll_new_workspaces', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_index(op.f('ix_mcp_credential_grants_install_id'), table_name='mcp_credential_grants')
    op.drop_constraint(op.f('mcp_credential_grants_install_id_fkey'), 'mcp_credential_grants', type_='foreignkey')
    op.drop_column('mcp_credential_grants', 'install_id')
    op.drop_index(op.f('ix_mcp_workspace_connector_states_install_id'), table_name='mcp_workspace_connector_states')
    op.drop_constraint(op.f('mcp_workspace_connector_states_install_id_fkey'), 'mcp_workspace_connector_states', type_='foreignkey')
    op.drop_column('mcp_workspace_connector_states', 'install_id')
    op.drop_index(op.f('ix_mcp_connector_installs_org_id'), table_name='mcp_connector_installs')
    op.drop_index(op.f('ix_mcp_connector_installs_template_id'), table_name='mcp_connector_installs')
    op.drop_index(op.f('ix_mcp_connector_installs_workspace_id'), table_name='mcp_connector_installs')
    op.drop_index(op.f('uq_mcp_connector_install_slug_per_org'), table_name='mcp_connector_installs', postgresql_where="((install_state)::text = 'active'::text)")
    op.drop_index(op.f('uq_mcp_connector_install_template_per_org'), table_name='mcp_connector_installs', postgresql_where="(((install_state)::text = 'active'::text) AND (template_id IS NOT NULL))")
    op.drop_index(op.f('uq_mcp_connector_install_url_per_org'), table_name='mcp_connector_installs', postgresql_where="((install_state)::text = 'active'::text)")
    op.drop_table('mcp_connector_installs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_workspace_connector_states', sa.Column('install_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mcp_workspace_connector_states_install_id_fkey'), 'mcp_workspace_connector_states', 'mcp_connector_installs', ['install_id'], ['id'])
    op.create_index(op.f('ix_mcp_workspace_connector_states_install_id'), 'mcp_workspace_connector_states', ['install_id'], unique=False)
    op.add_column('mcp_credential_grants', sa.Column('install_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mcp_credential_grants_install_id_fkey'), 'mcp_credential_grants', 'mcp_connector_installs', ['install_id'], ['id'])
    op.create_index(op.f('ix_mcp_credential_grants_install_id'), 'mcp_credential_grants', ['install_id'], unique=False)
    op.drop_column('mcp_connectors', 'auto_enroll_new_workspaces')
    op.drop_column('mcp_connectors', 'sse_read_timeout')
    op.drop_column('mcp_connectors', 'timeout')
    op.drop_column('mcp_connectors', 'last_discovered_at')
    op.drop_column('mcp_connectors', 'discovery_metadata')
    op.drop_column('mcp_connectors', 'headers')
    op.drop_column('mcp_connectors', 'auth_status')
    op.drop_column('mcp_connectors', 'default_credential_policy')
    op.create_table('mcp_connector_installs',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('install_scope', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('server_url_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('transport', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('default_credential_policy', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('auth_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('discovery_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('install_state', sa.VARCHAR(length=16), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('oauth_client_config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('tools_cache', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('tool_citations', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('last_discovered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('timeout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sse_read_timeout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('auto_enroll_new_workspaces', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('discovery_metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('slug_name', sa.VARCHAR(length=72), server_default=sa.text("'mcp'::character varying"), autoincrement=False, nullable=False),
    sa.Column('static_auth_style', sa.VARCHAR(length=16), server_default=sa.text("'bearer'::character varying"), autoincrement=False, nullable=False),
    sa.Column('static_auth_header_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('static_auth_query_param', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.CheckConstraint("auth_method::text = ANY (ARRAY['oauth'::character varying, 'static'::character varying, 'none'::character varying]::text[])", name=op.f('ck_mcp_connector_installs_auth_method')),
    sa.CheckConstraint("install_scope::text = ANY (ARRAY['org'::character varying, 'workspace'::character varying]::text[])", name=op.f('ck_mcp_connector_installs_scope')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('mcp_connector_installs_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('mcp_connector_installs_org_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['mcp_connector_templates.id'], name=op.f('mcp_connector_installs_template_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('mcp_connector_installs_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mcp_connector_installs_pkey'))
    )
    op.create_index(op.f('uq_mcp_connector_install_url_per_org'), 'mcp_connector_installs', ['org_id', 'server_url_hash'], unique=True, postgresql_where="((install_state)::text = 'active'::text)")
    op.create_index(op.f('uq_mcp_connector_install_template_per_org'), 'mcp_connector_installs', ['org_id', 'template_id'], unique=True, postgresql_where="(((install_state)::text = 'active'::text) AND (template_id IS NOT NULL))")
    op.create_index(op.f('uq_mcp_connector_install_slug_per_org'), 'mcp_connector_installs', ['org_id', 'slug_name'], unique=True, postgresql_where="((install_state)::text = 'active'::text)")
    op.create_index(op.f('ix_mcp_connector_installs_workspace_id'), 'mcp_connector_installs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_mcp_connector_installs_template_id'), 'mcp_connector_installs', ['template_id'], unique=False)
    op.create_index(op.f('ix_mcp_connector_installs_org_id'), 'mcp_connector_installs', ['org_id'], unique=False)
    # ### end Alembic commands ###
