"""egress refs

Revision ID: a9a7473ed679
Revises: e74c8c264ad2
Create Date: 2026-05-26 02:03:04.283832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'a9a7473ed679'
down_revision: Union[str, Sequence[str], None] = 'e74c8c264ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egress_refs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ref_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sandbox_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('bindings', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_egress_ref_hash', 'egress_refs', ['ref_hash'], unique=True)
    op.create_index('ix_egress_ref_sandbox', 'egress_refs', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_egress_refs_org_id'), 'egress_refs', ['org_id'], unique=False)
    op.create_index(op.f('ix_egress_refs_sandbox_id'), 'egress_refs', ['sandbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_egress_refs_sandbox_id'), table_name='egress_refs')
    op.drop_index(op.f('ix_egress_refs_org_id'), table_name='egress_refs')
    op.drop_index('ix_egress_ref_sandbox', table_name='egress_refs')
    op.drop_index('ix_egress_ref_hash', table_name='egress_refs')
    op.drop_table('egress_refs')
    # ### end Alembic commands ###
