"""add conversation_shares table with scope

Revision ID: ab40489adff0
Revises: 3e8d2018cdb9
Create Date: 2026-06-11 17:32:42.372754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab40489adff0'
down_revision: Union[str, Sequence[str], None] = '3e8d2018cdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_shares',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creator_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creator_display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scope', sa.Enum('workspace', 'org', 'public', name='sharescope'), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifacts_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_shares_conversation', 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_shares_creator', 'conversation_shares', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_shares_org_id'), 'conversation_shares', ['org_id'], unique=False)
    op.create_index('ix_conversation_shares_org_ws', 'conversation_shares', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_conversation_shares_workspace_id'), 'conversation_shares', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_shares_workspace_id'), table_name='conversation_shares')
    op.drop_index('ix_conversation_shares_org_ws', table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_org_id'), table_name='conversation_shares')
    op.drop_index('ix_conversation_shares_creator', table_name='conversation_shares')
    op.drop_index('ix_conversation_shares_conversation', table_name='conversation_shares')
    op.drop_table('conversation_shares')
    # ### end Alembic commands ###
