"""add presented_files table

Revision ID: acacbbde0622
Revises: a1b2c3d4e5f6
Create Date: 2026-08-12 19:37:35.278587

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acacbbde0622"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "presented_files",
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "conversation_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("source_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("object_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column(
            "thumbnail_object_key",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            nullable=True,
        ),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("caption", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_presented_files_conversation_id",
        "presented_files",
        ["conversation_id"],
        unique=False,
    )
    op.create_index("ix_presented_files_org_id", "presented_files", ["org_id"], unique=False)
    op.create_index(
        "ix_presented_files_workspace_id",
        "presented_files",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_presented_files_org_ws",
        "presented_files",
        ["org_id", "workspace_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_presented_files_org_ws", table_name="presented_files")
    op.drop_index("ix_presented_files_workspace_id", table_name="presented_files")
    op.drop_index("ix_presented_files_org_id", table_name="presented_files")
    op.drop_index("ix_presented_files_conversation_id", table_name="presented_files")
    op.drop_table("presented_files")
