"""provider capability + liveness + model test columns

Revision ID: affde7178172
Revises: 00948a73877f
Create Date: 2026-05-20 06:19:51.227012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'affde7178172'
down_revision: Union[str, Sequence[str], None] = '00948a73877f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('last_test_at', sa.DateTime(), nullable=True))
    op.add_column('models', sa.Column('last_test_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.add_column('models', sa.Column('last_test_summary', sa.JSON(), nullable=True))
    op.add_column('providers', sa.Column('preset_slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('providers', sa.Column('capability', sa.JSON(), nullable=True))
    op.add_column('providers', sa.Column('model_capability_overrides', sa.JSON(), nullable=True))
    op.add_column('providers', sa.Column('last_liveness_at', sa.DateTime(), nullable=True))
    op.add_column('providers', sa.Column('last_liveness_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.add_column('providers', sa.Column('last_liveness_summary', sa.JSON(), nullable=True))
    op.execute("UPDATE providers SET provider_type = 'openai-completions' WHERE provider_type = 'openai_compat'")
    op.execute("UPDATE providers SET provider_type = 'anthropic-messages' WHERE provider_type = 'anthropic'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE providers SET provider_type = 'openai_compat' WHERE provider_type = 'openai-completions'")
    op.execute("UPDATE providers SET provider_type = 'anthropic' WHERE provider_type = 'anthropic-messages'")
    op.drop_column('providers', 'last_liveness_summary')
    op.drop_column('providers', 'last_liveness_status')
    op.drop_column('providers', 'last_liveness_at')
    op.drop_column('providers', 'model_capability_overrides')
    op.drop_column('providers', 'capability')
    op.drop_column('providers', 'preset_slug')
    op.drop_column('models', 'last_test_summary')
    op.drop_column('models', 'last_test_status')
    op.drop_column('models', 'last_test_at')
    # ### end Alembic commands ###
