"""add memory_items

Revision ID: b0def3f44ade
Revises: f814a7a7d90e
Create Date: 2026-05-09 00:55:49.637436

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0def3f44ade'
down_revision: Union[str, Sequence[str], None] = 'f814a7a7d90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scope', sa.Enum('PERSONAL', 'WORKSPACE', 'ORG', name='memoryscope'), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('type', sa.Enum('PREFERENCE', 'PROJECT_FACT', 'PROCEDURE', 'CORRECTION', 'DECISION', 'ORG_POLICY', name='memorytype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='memorystatus'), nullable=False),
    sa.Column('source_type', sa.Enum('CONVERSATION', 'TOOL_RESULT', 'ARTIFACT', 'MANUAL', 'IMPORT', name='memorysourcetype'), nullable=False),
    sa.Column('source_conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('source_run_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('source_artifact_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('source_excerpt', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('updated_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint(
        "(scope = 'PERSONAL' AND owner_user_id IS NOT NULL "
        "AND org_id IS NULL AND workspace_id IS NULL) "
        "OR (scope = 'WORKSPACE' AND workspace_id IS NOT NULL "
        "AND org_id IS NOT NULL AND owner_user_id IS NULL) "
        "OR (scope = 'ORG' AND org_id IS NOT NULL "
        "AND workspace_id IS NULL AND owner_user_id IS NULL)",
        name="ck_memory_scope_targets",
    ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_org', 'memory_items', ['scope', 'org_id'], unique=False)
    op.create_index('ix_memory_personal', 'memory_items', ['scope', 'owner_user_id'], unique=False)
    op.create_index('ix_memory_status', 'memory_items', ['status'], unique=False)
    op.create_index('ix_memory_workspace', 'memory_items', ['scope', 'workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_workspace', table_name='memory_items')
    op.drop_index('ix_memory_status', table_name='memory_items')
    op.drop_index('ix_memory_personal', table_name='memory_items')
    op.drop_index('ix_memory_org', table_name='memory_items')
    op.drop_table('memory_items')
    sa.Enum(name="memorysourcetype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="memorystatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="memorytype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="memoryscope").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
