"""group_chat_and_conversation_participants

Revision ID: b5242b73e9ce
Revises: bed4e0f0065c
Create Date: 2026-06-18 12:48:40.574596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'b5242b73e9ce'
down_revision: Union[str, Sequence[str], None] = 'bed4e0f0065c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('topics',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creator_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sandbox_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topics_creator', 'topics', ['creator_user_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_topics_org_id'), 'topics', ['org_id'], unique=False)
    op.create_index('ix_topics_org_ws', 'topics', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_topics_workspace_id'), 'topics', ['workspace_id'], unique=False)
    op.create_table('topic_participants',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'user_id', name='uq_topic_participant')
    )
    op.create_index(op.f('ix_topic_participants_topic_id'), 'topic_participants', ['topic_id'], unique=False)
    op.create_index('ix_topic_participants_user', 'topic_participants', ['user_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_org_id'), 'conversation_participants', ['org_id'], unique=False)
    op.create_index('ix_conversation_participants_user', 'conversation_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_workspace_id'), 'conversation_participants', ['workspace_id'], unique=False)
    op.add_column('conversations', sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('conversations', sa.Column('is_group_chat', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('conversations', 'is_group_chat', server_default=None)
    op.create_index('ix_conversations_topic', 'conversations', ['topic_id'], unique=False)
    op.create_foreign_key('fk_conversations_topic_id_topics', 'conversations', 'topics', ['topic_id'], ['id'])
    op.add_column('user_sandboxes', sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='user'))
    op.add_column('user_sandboxes', sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=''))
    # Backfill: every pre-existing user_sandboxes row was keyed by
    # ``user_id`` only. The new polymorphic scope is ``('user', user_id)``
    # — without this UPDATE the existing rows get ``scope_id=''`` from
    # the column default and become unreachable via
    # ``get_active_by_scope('user', real_user_id)``.
    op.execute(
        "UPDATE user_sandboxes SET scope_id = user_id "
        "WHERE scope_id = '' OR scope_id IS NULL"
    )
    op.execute(
        "UPDATE user_sandboxes SET scope_type = 'user' "
        "WHERE scope_type = '' OR scope_type IS NULL"
    )
    op.alter_column('user_sandboxes', 'scope_type', server_default=None)
    op.alter_column('user_sandboxes', 'scope_id', server_default=None)
    op.drop_index('uq_user_sandbox_active', table_name='user_sandboxes', postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))
    op.create_index('uq_user_sandbox_active_scope', 'user_sandboxes', ['org_id', 'workspace_id', 'scope_type', 'scope_id'], unique=True, postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_user_sandbox_active_scope', table_name='user_sandboxes', postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))
    op.create_index('uq_user_sandbox_active', 'user_sandboxes', ['org_id', 'workspace_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('provisioning','running')"), sqlite_where=sa.text("status IN ('provisioning','running')"))
    op.drop_column('user_sandboxes', 'scope_id')
    op.drop_column('user_sandboxes', 'scope_type')
    op.drop_constraint('fk_conversations_topic_id_topics', 'conversations', type_='foreignkey')
    op.drop_index('ix_conversations_topic', table_name='conversations')
    op.drop_column('conversations', 'is_group_chat')
    op.drop_column('conversations', 'topic_id')
    op.drop_index(op.f('ix_conversation_participants_workspace_id'), table_name='conversation_participants')
    op.drop_index('ix_conversation_participants_user', table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_org_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_topic_participants_user', table_name='topic_participants')
    op.drop_index(op.f('ix_topic_participants_topic_id'), table_name='topic_participants')
    op.drop_table('topic_participants')
    op.drop_index(op.f('ix_topics_workspace_id'), table_name='topics')
    op.drop_index('ix_topics_org_ws', table_name='topics')
    op.drop_index(op.f('ix_topics_org_id'), table_name='topics')
    op.drop_index('ix_topics_creator', table_name='topics')
    op.drop_table('topics')
