"""short prefixed public ids and unified timestamps

Revision ID: bd12d3efd95b
Revises: 49ec26f0f17c
Create Date: 2026-05-05 20:05:14.749984

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd12d3efd95b'
down_revision: Union[str, Sequence[str], None] = '49ec26f0f17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('agent_configs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('agent_configs', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('agent_configs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'agent_configs', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'agent_configs', 'organizations', ['org_id'], ['id'])
    op.add_column('artifact_versions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('artifact_versions', 'id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifact_versions', 'artifact_id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifact_versions', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifact_versions', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'artifact_versions', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'artifact_versions', 'organizations', ['org_id'], ['id'])
    op.alter_column('artifacts', 'id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifacts', 'conversation_id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifacts', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('artifacts', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'artifacts', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'artifacts', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('attachments', 'id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('attachments', 'conversation_id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('attachments', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('attachments', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('attachments', 'uploader_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'attachments', 'users', ['uploader_user_id'], ['id'])
    op.create_foreign_key(None, 'attachments', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'attachments', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('billing_events', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('billing_events', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_events', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_events', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_events', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_events', 'conversation_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'billing_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'billing_events', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'billing_events', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'billing_events', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('billing_llm_events', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('billing_llm_events', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('billing_llm_events', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'billing_event_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'parent_run_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=True)
    op.alter_column('conversations', 'id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('conversations', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('conversations', 'creator_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'conversations', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['creator_user_id'], ['id'])
    op.alter_column('credentials', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('credentials', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('credentials', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'credentials', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'credentials', 'organizations', ['org_id'], ['id'])
    op.alter_column('invite_tokens', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('invite_tokens', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'invite_tokens', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'invite_tokens', 'users', ['created_by'], ['id'])
    op.alter_column('mcp_servers', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('mcp_servers', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('mcp_servers', 'owner_workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.alter_column('mcp_servers', 'credential_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.alter_column('mcp_servers', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'mcp_servers', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'mcp_servers', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'mcp_servers', 'credentials', ['credential_id'], ['id'])
    op.create_foreign_key(None, 'mcp_servers', 'workspaces', ['owner_workspace_id'], ['id'])
    op.add_column('memberships', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('memberships', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('memberships', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'memberships', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'])
    op.alter_column('models', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('models', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.alter_column('models', 'provider_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'models', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'models', 'providers', ['provider_id'], ['id'])
    op.add_column('org_preinstalled_tombstones', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('org_preinstalled_tombstones', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('org_preinstalled_tombstones', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'skill_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'hidden_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_org_preinstalled_tombstone'), 'org_preinstalled_tombstones', type_='unique')
    op.create_foreign_key(None, 'org_preinstalled_tombstones', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'org_preinstalled_tombstones', 'users', ['hidden_by_user_id'], ['id'])
    op.create_foreign_key(None, 'org_preinstalled_tombstones', 'skills', ['skill_id'], ['id'])
    op.drop_constraint('org_preinstalled_tombstones_pkey', 'org_preinstalled_tombstones', type_='primary')
    op.drop_column('org_preinstalled_tombstones', 'id')
    op.create_primary_key('org_preinstalled_tombstones_pkey', 'org_preinstalled_tombstones', ['org_id', 'skill_id'])
    op.alter_column('org_provider_overrides', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'provider_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'org_provider_overrides', 'providers', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'org_provider_overrides', 'organizations', ['org_id'], ['id'])
    op.alter_column('org_settings', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_org_settings_org_id'), table_name='org_settings')
    op.drop_constraint(op.f('uq_org_settings_org_key'), 'org_settings', type_='unique')
    op.create_foreign_key(None, 'org_settings', 'organizations', ['org_id'], ['id'])
    op.drop_constraint('org_settings_pkey', 'org_settings', type_='primary')
    op.drop_column('org_settings', 'id')
    op.create_primary_key('org_settings_pkey', 'org_settings', ['org_id', 'key'])
    op.add_column('org_skill_installs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('org_skill_installs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('org_skill_installs', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'skill_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'installed_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'org_skill_installs', 'users', ['installed_by_user_id'], ['id'])
    op.create_foreign_key(None, 'org_skill_installs', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'org_skill_installs', 'skills', ['skill_id'], ['id'])
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('organizations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('providers', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('providers', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.alter_column('providers', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               nullable=True)
    op.drop_index(op.f('uq_provider_system_name'), table_name='providers', postgresql_where='(org_id IS NULL)')
    op.create_foreign_key(None, 'providers', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'providers', 'organizations', ['org_id'], ['id'])
    op.add_column('skill_versions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('skill_versions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('skill_versions', 'skill_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('skill_versions', 'uploaded_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'skill_versions', 'users', ['uploaded_by_user_id'], ['id'])
    op.create_foreign_key(None, 'skill_versions', 'skills', ['skill_id'], ['id'])
    op.alter_column('skills', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('skills', 'owner_org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'skills', 'organizations', ['owner_org_id'], ['id'])
    op.alter_column('user_mcp_credentials', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'mcp_server_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'credential_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'oauth_refresh_token_credential_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'user_mcp_credentials', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_mcp_credentials', 'credentials', ['credential_id'], ['id'])
    op.create_foreign_key(None, 'user_mcp_credentials', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'user_mcp_credentials', 'credentials', ['oauth_refresh_token_credential_id'], ['id'])
    op.create_foreign_key(None, 'user_mcp_credentials', 'mcp_servers', ['mcp_server_id'], ['id'])
    op.add_column('user_sandboxes', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('user_sandboxes', 'id',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'user_sandboxes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_sandboxes', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'user_sandboxes', 'organizations', ['org_id'], ['id'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'mcp_server_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'workspace_mcp_bindings', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_bindings', 'mcp_servers', ['mcp_server_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_bindings', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_bindings', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('workspace_mcp_bindings_pkey', 'workspace_mcp_bindings', type_='primary')
    op.drop_column('workspace_mcp_bindings', 'id')
    op.create_primary_key('workspace_mcp_bindings_pkey', 'workspace_mcp_bindings', ['workspace_id', 'mcp_server_id'])
    op.alter_column('workspace_mcp_credentials', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'mcp_server_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'credential_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'workspace_mcp_credentials', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_credentials', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_credentials', 'mcp_servers', ['mcp_server_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_credentials', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'workspace_mcp_credentials', 'credentials', ['credential_id'], ['id'])
    op.add_column('workspace_skill_bindings', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('workspace_skill_bindings', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'org_skill_install_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_workspace_skill_binding'), 'workspace_skill_bindings', type_='unique')
    op.create_foreign_key(None, 'workspace_skill_bindings', 'org_skill_installs', ['org_skill_install_id'], ['id'])
    op.create_foreign_key(None, 'workspace_skill_bindings', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'workspace_skill_bindings', 'organizations', ['org_id'], ['id'])
    op.drop_constraint('workspace_skill_bindings_pkey', 'workspace_skill_bindings', type_='primary')
    op.drop_column('workspace_skill_bindings', 'id')
    op.create_primary_key(
        'workspace_skill_bindings_pkey', 'workspace_skill_bindings', ['workspace_id', 'org_skill_install_id']
    )
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('workspaces', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('workspaces', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'workspaces', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.alter_column('workspaces', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('workspaces', 'updated_at')
    op.drop_constraint('workspace_skill_bindings_pkey', 'workspace_skill_bindings', type_='primary')
    op.add_column('workspace_skill_bindings', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_primary_key('workspace_skill_bindings_pkey', 'workspace_skill_bindings', ['id'])
    op.drop_constraint(None, 'workspace_skill_bindings', type_='foreignkey')
    op.drop_constraint(None, 'workspace_skill_bindings', type_='foreignkey')
    op.drop_constraint(None, 'workspace_skill_bindings', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_workspace_skill_binding'), 'workspace_skill_bindings', ['workspace_id', 'org_skill_install_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workspace_skill_bindings', 'org_skill_install_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_skill_bindings', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('workspace_skill_bindings', 'updated_at')
    op.drop_constraint(None, 'workspace_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_credentials', type_='foreignkey')
    op.alter_column('workspace_mcp_credentials', 'created_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'credential_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'mcp_server_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_credentials', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint('workspace_mcp_bindings_pkey', 'workspace_mcp_bindings', type_='primary')
    op.add_column('workspace_mcp_bindings', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_primary_key('workspace_mcp_bindings_pkey', 'workspace_mcp_bindings', ['id'])
    op.drop_constraint(None, 'workspace_mcp_bindings', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_bindings', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_bindings', type_='foreignkey')
    op.drop_constraint(None, 'workspace_mcp_bindings', type_='foreignkey')
    op.alter_column('workspace_mcp_bindings', 'created_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'mcp_server_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspace_mcp_bindings', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'user_sandboxes', type_='foreignkey')
    op.drop_constraint(None, 'user_sandboxes', type_='foreignkey')
    op.drop_constraint(None, 'user_sandboxes', type_='foreignkey')
    op.alter_column('user_sandboxes', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_sandboxes', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('user_sandboxes', 'updated_at')
    op.drop_constraint(None, 'user_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'user_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'user_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'user_mcp_credentials', type_='foreignkey')
    op.drop_constraint(None, 'user_mcp_credentials', type_='foreignkey')
    op.alter_column('user_mcp_credentials', 'oauth_refresh_token_credential_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('user_mcp_credentials', 'credential_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'mcp_server_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_mcp_credentials', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.alter_column('skills', 'owner_org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('skills', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'skill_versions', type_='foreignkey')
    op.drop_constraint(None, 'skill_versions', type_='foreignkey')
    op.alter_column('skill_versions', 'uploaded_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('skill_versions', 'skill_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('skill_versions', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('skill_versions', 'updated_at')
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.create_index(op.f('uq_provider_system_name'), 'providers', ['name'], unique=True, postgresql_where='(org_id IS NULL)')
    op.alter_column('providers', 'created_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('providers', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('providers', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('organizations', 'updated_at')
    op.drop_constraint(None, 'org_skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'org_skill_installs', type_='foreignkey')
    op.drop_constraint(None, 'org_skill_installs', type_='foreignkey')
    op.alter_column('org_skill_installs', 'installed_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'skill_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_skill_installs', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('org_skill_installs', 'updated_at')
    op.drop_column('org_skill_installs', 'created_at')
    op.drop_constraint('org_settings_pkey', 'org_settings', type_='primary')
    op.add_column('org_settings', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_primary_key('org_settings_pkey', 'org_settings', ['id'])
    op.drop_constraint(None, 'org_settings', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_org_settings_org_key'), 'org_settings', ['org_id', 'key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_org_settings_org_id'), 'org_settings', ['org_id'], unique=False)
    op.alter_column('org_settings', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'org_provider_overrides', type_='foreignkey')
    op.drop_constraint(None, 'org_provider_overrides', type_='foreignkey')
    op.alter_column('org_provider_overrides', 'provider_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_provider_overrides', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint('org_preinstalled_tombstones_pkey', 'org_preinstalled_tombstones', type_='primary')
    op.add_column('org_preinstalled_tombstones', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_primary_key('org_preinstalled_tombstones_pkey', 'org_preinstalled_tombstones', ['id'])
    op.drop_constraint(None, 'org_preinstalled_tombstones', type_='foreignkey')
    op.drop_constraint(None, 'org_preinstalled_tombstones', type_='foreignkey')
    op.drop_constraint(None, 'org_preinstalled_tombstones', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_org_preinstalled_tombstone'), 'org_preinstalled_tombstones', ['org_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('org_preinstalled_tombstones', 'hidden_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'skill_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('org_preinstalled_tombstones', 'updated_at')
    op.drop_column('org_preinstalled_tombstones', 'created_at')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.alter_column('models', 'provider_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('models', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('models', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.alter_column('memberships', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('memberships', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('memberships', 'updated_at')
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.alter_column('mcp_servers', 'created_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('mcp_servers', 'credential_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('mcp_servers', 'owner_workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('mcp_servers', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('mcp_servers', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'invite_tokens', type_='foreignkey')
    op.drop_constraint(None, 'invite_tokens', type_='foreignkey')
    op.alter_column('invite_tokens', 'created_by',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('invite_tokens', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.alter_column('credentials', 'created_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('credentials', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('credentials', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'creator_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'parent_run_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('billing_llm_events', 'billing_event_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_llm_events', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('billing_llm_events', 'updated_at')
    op.drop_column('billing_llm_events', 'created_at')
    op.drop_constraint(None, 'billing_events', type_='foreignkey')
    op.drop_constraint(None, 'billing_events', type_='foreignkey')
    op.drop_constraint(None, 'billing_events', type_='foreignkey')
    op.drop_constraint(None, 'billing_events', type_='foreignkey')
    op.alter_column('billing_events', 'conversation_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_events', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_events', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_events', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('billing_events', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('billing_events', 'updated_at')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.alter_column('attachments', 'uploader_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('attachments', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('attachments', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.alter_column('artifacts', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('artifacts', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'artifact_versions', type_='foreignkey')
    op.drop_constraint(None, 'artifact_versions', type_='foreignkey')
    op.alter_column('artifact_versions', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('artifact_versions', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('artifact_versions', 'updated_at')
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.alter_column('agent_configs', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('agent_configs', 'workspace_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('agent_configs', 'org_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('agent_configs', 'created_at')
    # ### end Alembic commands ###
