"""cubepi v4 to v5 hitl answers

Revision ID: c2f1a7b9d340
Revises: ecb4ae85960c
Create Date: 2026-06-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'c2f1a7b9d340'
down_revision: Union[str, Sequence[str], None] = 'ecb4ae85960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Hand-added: cubepi v4 -> v5 schema upgrade.
    #
    # autogenerate produces an empty diff because the cubepi_* tables are
    # listed in alembic/env.py's _CHECKPOINT_TABLES / cubepi_*_p prefix
    # guards (see the v3->v4 migration for the same pattern). The upstream
    # helper is the only correct source of these statements.
    #
    # upgrade_v4_to_v5_op() adds:
    #   * cubepi_hitl_answers table (CREATE TABLE IF NOT EXISTS) with
    #     PK (thread_id, run_id, question_id) and
    #     FK (thread_id) -> cubepi_threads ON DELETE CASCADE
    #     — durable HITL answer ledger for parallel-approval replay across
    #     cross-process resume (cubepi 0.12.0).
    #
    # EXPECTED_SCHEMA_VERSION is now 5; PostgresCheckpointer refuses to
    # enter context until cubepi_schema_version matches, so the version
    # row bump via write_schema_version_op() is mandatory.
    from cubepi.checkpointer.postgres.alembic_helpers import (
        upgrade_v4_to_v5_op,
        write_schema_version_op,
    )

    op.execute(upgrade_v4_to_v5_op())
    op.execute(write_schema_version_op())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Hand-added: symmetric drop. The table has no partitions, so a plain
    # DROP IF EXISTS suffices. Revert cubepi_schema_version back to 4.
    op.execute("DROP TABLE IF EXISTS cubepi_hitl_answers")
    op.execute(
        "DELETE FROM cubepi_schema_version WHERE version <> 4; "
        "INSERT INTO cubepi_schema_version (version) VALUES (4) "
        "ON CONFLICT DO NOTHING;"
    )
