"""make skill install and tombstone user FKs nullable

Revision ID: c8bbfbf153b6
Revises: 828846c2dada
Create Date: 2026-06-11 23:57:12.742721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'c8bbfbf153b6'
down_revision: Union[str, Sequence[str], None] = '828846c2dada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_preinstalled_tombstones', 'hidden_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('org_skill_installs', 'installed_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_skill_installs', 'installed_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('org_preinstalled_tombstones', 'hidden_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
