"""add credentials table

Revision ID: cb2c39969ef1
Revises: 7bb73b55aa6a
Create Date: 2026-04-30 15:55:23.429000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb2c39969ef1"
down_revision: str | Sequence[str] | None = "7bb73b55aa6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("value_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("cred_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_by_user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "kind", "name", name="uq_credential_org_kind_name"),
    )
    op.create_index(op.f("ix_credentials_org_id"), "credentials", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credentials_org_id"), table_name="credentials")
    op.drop_table("credentials")
    # ### end Alembic commands ###
