"""scheduled_tasks

Revision ID: d081288c6c35
Revises: 1f65e338699a
Create Date: 2026-05-28 04:12:46.906484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'd081288c6c35'
down_revision: Union[str, Sequence[str], None] = '1f65e338699a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('schedule_kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('next_fire_at', sa.DateTime(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_tasks_deleted_at_partial', 'scheduled_tasks', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index(op.f('ix_scheduled_tasks_next_fire_at'), 'scheduled_tasks', ['next_fire_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_org_id'), 'scheduled_tasks', ['org_id'], unique=False)
    op.create_index('ix_scheduled_tasks_org_ws', 'scheduled_tasks', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_owner_user_id'), 'scheduled_tasks', ['owner_user_id'], unique=False)
    op.create_index('ix_scheduled_tasks_status_next_fire', 'scheduled_tasks', ['status', 'next_fire_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_workspace_id'), 'scheduled_tasks', ['workspace_id'], unique=False)
    op.create_table('scheduled_task_runs',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scheduled_task_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scheduled_task_id'], ['scheduled_tasks.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_task_id', 'scheduled_for', name='uq_stkrn_task_scheduled_for')
    )
    op.create_index(op.f('ix_scheduled_task_runs_org_id'), 'scheduled_task_runs', ['org_id'], unique=False)
    op.create_index('ix_scheduled_task_runs_org_ws', 'scheduled_task_runs', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_scheduled_task_id'), 'scheduled_task_runs', ['scheduled_task_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_workspace_id'), 'scheduled_task_runs', ['workspace_id'], unique=False)
    op.create_index('ix_stkrn_run_id', 'scheduled_task_runs', ['run_id'], unique=False)
    op.create_index('ix_stkrn_state_claimed_at', 'scheduled_task_runs', ['state', 'claimed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stkrn_state_claimed_at', table_name='scheduled_task_runs')
    op.drop_index('ix_stkrn_run_id', table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_workspace_id'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_scheduled_task_id'), table_name='scheduled_task_runs')
    op.drop_index('ix_scheduled_task_runs_org_ws', table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_org_id'), table_name='scheduled_task_runs')
    op.drop_table('scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_tasks_workspace_id'), table_name='scheduled_tasks')
    op.drop_index('ix_scheduled_tasks_status_next_fire', table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_owner_user_id'), table_name='scheduled_tasks')
    op.drop_index('ix_scheduled_tasks_org_ws', table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_org_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_next_fire_at'), table_name='scheduled_tasks')
    op.drop_index('ix_scheduled_tasks_deleted_at_partial', table_name='scheduled_tasks', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
