"""add attachment cols to im_run_queue

Revision ID: d1f37c369298
Revises: 2031a448c1f6
Create Date: 2026-06-24 16:55:22.357776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'd1f37c369298'
down_revision: Union[str, Sequence[str], None] = '2031a448c1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('im_run_queue', sa.Column('attachment_refs', sa.JSON(), nullable=True))
    op.add_column('im_run_queue', sa.Column('attachment_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('im_run_queue', 'attachment_ids')
    op.drop_column('im_run_queue', 'attachment_refs')
    # ### end Alembic commands ###
