"""sandbox pause resume columns

Revision ID: d38ab8f46a25
Revises: 6c69cc288404
Create Date: 2026-05-28 03:38:45.212558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'd38ab8f46a25'
down_revision: Union[str, Sequence[str], None] = '6c69cc288404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sandboxes', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), server_default='opensandbox', nullable=False))
    op.add_column('user_sandboxes', sa.Column('paused_at', sa.DateTime(), nullable=True))
    op.add_column('user_sandboxes', sa.Column('paused_ttl_seconds', sa.Integer(), server_default='1440', nullable=False))
    op.add_column('user_sandboxes', sa.Column('last_resumed_at', sa.DateTime(), nullable=True))
    op.add_column('user_sandboxes', sa.Column('in_use_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_sandboxes_in_use_until'), 'user_sandboxes', ['in_use_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sandboxes_in_use_until'), table_name='user_sandboxes')
    op.drop_column('user_sandboxes', 'in_use_until')
    op.drop_column('user_sandboxes', 'last_resumed_at')
    op.drop_column('user_sandboxes', 'paused_ttl_seconds')
    op.drop_column('user_sandboxes', 'paused_at')
    op.drop_column('user_sandboxes', 'provider')
    # ### end Alembic commands ###
