"""add reflection to memorysourcetype enum

Revision ID: d6745d82b6be
Revises: 375b2771c56e
Create Date: 2026-06-02 22:31:45.100266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'd6745d82b6be'
down_revision: Union[str, Sequence[str], None] = '375b2771c56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the 'REFLECTION' value to the memorysourcetype Postgres enum.

    The detached reflection runner writes MemoryItem.source_type=REFLECTION
    (via the reflection_context ContextVar); without this value the first such
    insert fails with an invalid-enum error. Alembic autogenerate does NOT
    emit ALTER TYPE ... ADD VALUE, so this is hand-written. Run outside a
    transaction (autocommit) for cross-version safety. Mirrors 1890ff8246f4
    (consolidation).
    """
    # SQLAlchemy stores Python Enum members by NAME, so the existing labels
    # are the uppercase names (CONVERSATION, MANUAL, …) — add the NAME, not
    # the lowercase .value.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE memorysourcetype ADD VALUE IF NOT EXISTS 'REFLECTION'")


def downgrade() -> None:
    """No-op: Postgres has no DROP VALUE for enums; removing a value safely
    would require recreating the type and rewriting every dependent column.
    Leave it."""
    pass
