"""make user-FK columns nullable on mcp/skill_registry tables

Revision ID: d954724a1032
Revises: 33ac667bd514
Create Date: 2026-06-11 21:25:39.079500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'd954724a1032'
down_revision: Union[str, Sequence[str], None] = '33ac667bd514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_connector_installs', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('mcp_credential_grants', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('mcp_workspace_connector_states', 'updated_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('skill_registries', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_registries', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('mcp_workspace_connector_states', 'updated_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('mcp_credential_grants', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('mcp_connector_installs', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
