"""rename skill_sources to skill_registries

Revision ID: e0a411d361fb
Revises: e2dbb11407ca
Create Date: 2026-05-31 00:49:47.993215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'e0a411d361fb'
down_revision: Union[str, Sequence[str], None] = '2f3d624337bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.rename_table("skill_sources", "skill_registries")
    # PostgreSQL does not auto-rename indexes on table rename; fix the name so
    # Alembic autogenerate stays clean.
    op.execute("ALTER INDEX IF EXISTS ix_skill_sources_org_id RENAME TO ix_skill_registries_org_id")


def downgrade() -> None:
    op.execute("ALTER INDEX IF EXISTS ix_skill_registries_org_id RENAME TO ix_skill_sources_org_id")
    op.rename_table("skill_registries", "skill_sources")
