"""skill registries: rename table, add imported_from fields to skills

Revision ID: e0a411d361fb
Revises: 2f3d624337bd
Create Date: 2026-05-31 00:49:47.993215

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0a411d361fb"
down_revision: Union[str, Sequence[str], None] = "2f3d624337bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rename skill_sources → skill_registries
    op.rename_table("skill_sources", "skill_registries")
    # PostgreSQL does not auto-rename indexes on table rename.
    op.execute(
        "ALTER INDEX IF EXISTS ix_skill_sources_org_id RENAME TO ix_skill_registries_org_id"
    )

    # Track which registry a skill was imported from and the exact fetch path
    op.add_column(
        "skills",
        sa.Column(
            "imported_from_registry_id",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_skills_imported_from_registry",
        "skills",
        "skill_registries",
        ["imported_from_registry_id"],
        ["id"],
    )
    op.add_column(
        "skills",
        sa.Column(
            "imported_from_source_ref",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("skills", "imported_from_source_ref")
    op.drop_constraint("fk_skills_imported_from_registry", "skills", type_="foreignkey")
    op.drop_column("skills", "imported_from_registry_id")
    op.execute(
        "ALTER INDEX IF EXISTS ix_skill_registries_org_id RENAME TO ix_skill_sources_org_id"
    )
    op.rename_table("skill_registries", "skill_sources")
