"""add end_at to scheduled_tasks

Revision ID: e2dbb11407ca
Revises: fdcc495b3704
Create Date: 2026-05-30 16:24:03.377303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'e2dbb11407ca'
down_revision: Union[str, Sequence[str], None] = 'fdcc495b3704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('end_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_tasks', 'end_at')
    # ### end Alembic commands ###
