"""sandbox env vars

Revision ID: e74c8c264ad2
Revises: 1890ff8246f4
Create Date: 2026-05-26 00:41:36.021912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'e74c8c264ad2'
down_revision: Union[str, Sequence[str], None] = '1890ff8246f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_env_vars',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('env_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('hosts', sa.JSON(), nullable=True),
    sa.Column('header_names', sa.JSON(), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('plain_value', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.CheckConstraint("(scope='org' AND workspace_id IS NULL AND user_id IS NULL) OR (scope='workspace' AND workspace_id IS NOT NULL AND user_id IS NULL) OR (scope='user' AND workspace_id IS NOT NULL AND user_id IS NOT NULL)", name='ck_sandbox_env_scope_columns'),
    sa.CheckConstraint("scope IN ('org','workspace','user')", name='ck_sandbox_env_scope'),
    sa.CheckConstraint('(is_secret AND credential_id IS NOT NULL AND plain_value IS NULL AND hosts IS NOT NULL) OR (NOT is_secret AND plain_value IS NOT NULL AND credential_id IS NULL AND hosts IS NULL)', name='ck_sandbox_env_value_shape'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_env_vars_org_id'), 'sandbox_env_vars', ['org_id'], unique=False)
    op.create_index(op.f('ix_sandbox_env_vars_user_id'), 'sandbox_env_vars', ['user_id'], unique=False)
    op.create_index(op.f('ix_sandbox_env_vars_workspace_id'), 'sandbox_env_vars', ['workspace_id'], unique=False)
    op.create_index('uq_sandbox_env_org', 'sandbox_env_vars', ['org_id', 'env_name'], unique=True, postgresql_where="scope = 'org'")
    op.create_index('uq_sandbox_env_user', 'sandbox_env_vars', ['workspace_id', 'user_id', 'env_name'], unique=True, postgresql_where="scope = 'user'")
    op.create_index('uq_sandbox_env_workspace', 'sandbox_env_vars', ['workspace_id', 'env_name'], unique=True, postgresql_where="scope = 'workspace'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sandbox_env_workspace', table_name='sandbox_env_vars', postgresql_where="scope = 'workspace'")
    op.drop_index('uq_sandbox_env_user', table_name='sandbox_env_vars', postgresql_where="scope = 'user'")
    op.drop_index('uq_sandbox_env_org', table_name='sandbox_env_vars', postgresql_where="scope = 'org'")
    op.drop_index(op.f('ix_sandbox_env_vars_workspace_id'), table_name='sandbox_env_vars')
    op.drop_index(op.f('ix_sandbox_env_vars_user_id'), table_name='sandbox_env_vars')
    op.drop_index(op.f('ix_sandbox_env_vars_org_id'), table_name='sandbox_env_vars')
    op.drop_table('sandbox_env_vars')
    # ### end Alembic commands ###
