"""conversation reasoning json

Revision ID: e7622d917897
Revises: f69d266f0367
Create Date: 2026-07-03 13:30:36.833850

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7622d917897"
down_revision: str | Sequence[str] | None = "f69d266f0367"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("reasoning", sa.JSON(), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE conversations
            SET reasoning = CASE thinking
                WHEN 'off' THEN '{"mode":"off","effort":"minimal","summary":"none"}'::json
                WHEN 'low' THEN '{"mode":"on","effort":"low","summary":"none"}'::json
                WHEN 'medium' THEN '{"mode":"on","effort":"medium","summary":"none"}'::json
                WHEN 'high' THEN '{"mode":"on","effort":"high","summary":"none"}'::json
                WHEN 'xhigh' THEN '{"mode":"on","effort":"max","summary":"none"}'::json
                ELSE '{"mode":"off","effort":"medium","summary":"none"}'::json
            END
            """
        )
    )
    op.alter_column("conversations", "reasoning", nullable=False)
    op.drop_column("conversations", "thinking")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "thinking",
            sa.VARCHAR(length=16),
            server_default=sa.text("'medium'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute(
        sa.text(
            """
            UPDATE conversations
            SET thinking = CASE
                WHEN reasoning->>'mode' = 'off' THEN 'off'
                WHEN reasoning->>'effort' = 'max' THEN 'xhigh'
                WHEN reasoning->>'effort' IN ('low', 'medium', 'high') THEN reasoning->>'effort'
                ELSE 'medium'
            END
            """
        )
    )
    op.drop_column("conversations", "reasoning")
    # ### end Alembic commands ###
