"""add triggers and trigger_events

Revision ID: ea209f51b410
Revises: 6c69cc288404
Create Date: 2026-05-28 05:43:58.536184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'ea209f51b410'
down_revision: Union[str, Sequence[str], None] = 'd081288c6c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('filter', sa.JSON(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_ref', sa.JSON(), nullable=True),
    sa.Column('payload_fields', sa.JSON(), nullable=True),
    sa.Column('conversation_policy', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('run_as_user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('max_runs_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_burst', sa.Integer(), nullable=False),
    sa.Column('rate_limit_response', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('current_secret_cred_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('previous_secret_cred_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('previous_secret_expires_at', sa.DateTime(), nullable=True),
    sa.Column('events_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('events_success', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('events_failed', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('events_dedup_dropped', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['current_secret_cred_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['previous_secret_cred_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['run_as_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_enabled'), 'triggers', ['enabled'], unique=False)
    op.create_index(op.f('ix_triggers_org_id'), 'triggers', ['org_id'], unique=False)
    op.create_index('ix_triggers_org_ws', 'triggers', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_triggers_workspace_id'), 'triggers', ['workspace_id'], unique=False)
    op.create_table('trigger_events',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trigger_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('resulting_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resulting_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_events_org_id'), 'trigger_events', ['org_id'], unique=False)
    op.create_index('ix_trigger_events_org_ws', 'trigger_events', ['org_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_trigger_id'), 'trigger_events', ['trigger_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_workspace_id'), 'trigger_events', ['workspace_id'], unique=False)
    op.create_index('uq_trigger_event_dedup', 'trigger_events', ['trigger_id', 'dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trigger_event_dedup', table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_workspace_id'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_trigger_id'), table_name='trigger_events')
    op.drop_index('ix_trigger_events_org_ws', table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_org_id'), table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_index(op.f('ix_triggers_workspace_id'), table_name='triggers')
    op.drop_index('ix_triggers_org_ws', table_name='triggers')
    op.drop_index(op.f('ix_triggers_org_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_enabled'), table_name='triggers')
    op.drop_table('triggers')
    # ### end Alembic commands ###
