"""add avatar columns to users

Revision ID: ecb4ae85960c
Revises: 7aec44dafed6
Create Date: 2026-06-27 04:57:40.620569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'ecb4ae85960c'
down_revision: Union[str, Sequence[str], None] = '7aec44dafed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_seed', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_style', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_style')
    op.drop_column('users', 'avatar_seed')
    op.drop_column('users', 'avatar_kind')
    # ### end Alembic commands ###
