"""add api_keys table

Revision ID: f30c90a6392f
Revises: 0c41b322ea93
Create Date: 2026-06-23 04:53:24.762244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'f30c90a6392f'
down_revision: Union[str, Sequence[str], None] = '0c41b322ea93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('uq_api_keys_hashed_key', 'api_keys', ['hashed_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_api_keys_hashed_key', table_name='api_keys')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
