"""drop invite_tokens table

Revision ID: f69d266f0367
Revises: af15a08b4ce9
Create Date: 2026-07-01 19:59:01.472014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f69d266f0367'
down_revision: Union[str, Sequence[str], None] = 'af15a08b4ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_tokens_expires'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('invite_tokens_created_by_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('invite_tokens_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('token', name=op.f('invite_tokens_pkey'))
    )
    op.create_index(op.f('ix_invite_tokens_expires'), 'invite_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
