"""add imported_from_source_ref to skills

Revision ID: f96219f5725c
Revises: 9d19e2fa9777
Create Date: 2026-05-31 11:17:32.881841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'f96219f5725c'
down_revision: Union[str, Sequence[str], None] = '9d19e2fa9777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('skills', sa.Column('imported_from_source_ref', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('skills', 'imported_from_source_ref')
