"""cubepi v1 to v2 pending_request

Revision ID: fdcc495b3704
Revises: 28c4c57516f6
Create Date: 2026-05-29 13:24:05.951500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdcc495b3704'
down_revision: Union[str, Sequence[str], None] = '28c4c57516f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cubepi_threads', sa.Column('pending_request', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###

    # Hand-added: bump cubepi_schema_version 1 -> 2. This is a data row, not a
    # schema change, so autogenerate cannot emit it. Required — the cubepi pin
    # bump raised EXPECTED_SCHEMA_VERSION to 2 and PostgresCheckpointer refuses
    # to start on a v1 database.
    from cubepi.checkpointer.postgres.alembic_helpers import write_schema_version_op

    op.execute(write_schema_version_op())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cubepi_threads', 'pending_request')
    # ### end Alembic commands ###

    # Hand-added: revert cubepi_schema_version back to 1.
    op.execute(
        "DELETE FROM cubepi_schema_version WHERE version <> 1; "
        "INSERT INTO cubepi_schema_version (version) VALUES (1) ON CONFLICT DO NOTHING;"
    )
