"""add sso_connections and external_identities tables

Revision ID: ff70bc6d4f4f
Revises: 7c8f01bc8546
Create Date: 2026-06-17 21:54:48.442375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'ff70bc6d4f4f'
# Re-pointed from 'bed4e0f0065c' to '7c8f01bc8546' (main's tip at rebase time)
# to keep the alembic history linear after rebase, per AGENTS.md.
down_revision: Union[str, Sequence[str], None] = '7c8f01bc8546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('external_identities',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('external_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_identities_user_id', 'external_identities', ['user_id'], unique=False)
    op.create_index('uq_external_identity_provider', 'external_identities', ['provider_type', 'provider_id', 'external_id'], unique=True)
    op.create_table('sso_connections',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('provisioning', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_sso_connections_org_id')
    )
    op.create_index('ix_sso_connections_org_id', 'sso_connections', ['org_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_sso_connections_org_id', table_name='sso_connections')
    op.drop_table('sso_connections')
    op.drop_index('uq_external_identity_provider', table_name='external_identities')
    op.drop_index('ix_external_identities_user_id', table_name='external_identities')
    op.drop_table('external_identities')
