#!/usr/bin/env bash
# gen-ca.sh — Generate the fixed egress MITM CA and write it as a Kubernetes Secret.
#
# Run ONCE per cluster install.  The CA is long-lived (10 years) and must NOT be
# rotated without coordinating with the exchange endpoint (see Plan 2 config).
#
# IMPORTANT — same CA, dual purpose:
#   * The public cert (ca-cert.pem) is the CA the exchange server presents its TLS
#     cert under (server cert signed by this CA).  The addon/inject.py verifies
#     this CA when it calls the exchange endpoint.
#   * The CA is also the client-cert CA the exchange endpoint trusts
#     (ssl_ca_certs=<egress CA>).  Every per-sandbox client cert minted by the
#     webhook is signed by this CA, so the exchange can verify sidecar identity.
#
# Usage:
#   NAMESPACE=opensandbox ./scripts/gen-ca.sh
#
# Outputs:
#   deploy/kubernetes/egress-bundle/k8s/egress-mitm-ca-secret.yaml  (applied by the operator)
#
# Requirements:
#   - Python 3.11+ with the `cryptography` package (uv run --with cryptography works)
#   - kubectl in PATH (for the dry-run idempotency check)
#   - NAMESPACE env var (default: opensandbox)

set -euo pipefail

NAMESPACE="${NAMESPACE:-opensandbox}"
SECRET_NAME="egress-mitm-ca"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_YAML="${BUNDLE_DIR}/k8s/egress-mitm-ca-secret.yaml"

# --- idempotency check: refuse to overwrite if Secret already exists ---
if kubectl get secret "${SECRET_NAME}" --namespace "${NAMESPACE}" &>/dev/null; then
    echo "ERROR: Secret '${SECRET_NAME}' already exists in namespace '${NAMESPACE}'."
    echo "  To replace it you must manually delete it first:"
    echo "    kubectl delete secret ${SECRET_NAME} -n ${NAMESPACE}"
    echo "  WARNING: replacing the CA invalidates ALL existing per-sandbox client certs"
    echo "  and requires reconfiguring the exchange endpoint."
    exit 1
fi

# --- generate CA via the webhook cert_minter Python module ---
echo "Generating egress MITM CA ..."
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

python3 - "${TMPDIR}" "${BUNDLE_DIR}/webhook" <<'PYEOF'
import sys
import os
# __file__ is "<stdin>" for a piped heredoc, so the webhook dir is passed in
# from bash (argv[2]) rather than derived from __file__.
sys.path.insert(0, sys.argv[2])
from cert_minter import generate_ca  # type: ignore[import-untyped]

out = sys.argv[1]
key_pem, cert_pem = generate_ca("cubeplex-egress-mitm-ca")
with open(os.path.join(out, "mitmproxy-ca.pem"), "wb") as f:
    f.write(key_pem)
with open(os.path.join(out, "mitmproxy-ca-cert.pem"), "wb") as f:
    f.write(cert_pem)
with open(os.path.join(out, "ca-cert.pem"), "wb") as f:
    f.write(cert_pem)
print("CA generated.")
PYEOF

KEY_B64="$(base64 -w0 "${TMPDIR}/mitmproxy-ca.pem")"
CERT_B64="$(base64 -w0 "${TMPDIR}/mitmproxy-ca-cert.pem")"
PUB_B64="${CERT_B64}"   # same bytes, two keys in the Secret

# --- render the Secret YAML ---
cat > "${OUT_YAML}" <<YAML
# AUTO-GENERATED by scripts/gen-ca.sh — do not hand-edit.
# Apply with: kubectl apply -f k8s/egress-mitm-ca-secret.yaml -n ${NAMESPACE}
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: cubeplex-egress
type: Opaque
data:
  # RSA/EC private key for the MITM CA (used by the webhook to sign per-sandbox
  # client certs and by mitmproxy as its CA key).
  mitmproxy-ca.pem: ${KEY_B64}
  # Public CA certificate — mitmproxy confdir convention.
  mitmproxy-ca-cert.pem: ${CERT_B64}
  # Public CA certificate — generic alias used by the addon to verify the
  # exchange server cert and by initContainer CA trust install.
  ca-cert.pem: ${PUB_B64}
YAML

echo "Secret YAML written to: ${OUT_YAML}"
echo ""
echo "Next steps:"
echo "  kubectl apply -f ${OUT_YAML} -n ${NAMESPACE}"
echo "  Then configure the exchange endpoint (Plan 2) with:"
echo "    egress_exchange.tls.ca_cert = <path to mitmproxy-ca-cert.pem>"
echo "    egress_exchange.auth.mode   = mtls"
echo "    egress_exchange.auth.ca     = <path to mitmproxy-ca-cert.pem>"
